// ============================================================================
// Official Qatar Education System (LMS) Teacher Activity Report - September 2026
// تقرير تقييم المعلمين - مراجعة النشاط على المنصة - سبتمبر 2026
// تاريخ الإعداد: 20 سبتمبر 2026 | مدرسة قطر للعلوم والتكنولوجيا الإعدادية الثانوية للبنين
// ============================================================================

export interface LmsReportTeacherRecord {
  id: string;
  name: string;
  department: string;
  sectionsCount: number;
  subjectsAndSections: string;
  evalCoverageRatio: string;
  evalCoveragePercent: number;
  evalUploaded: number;
  evalAssigned: number;
  evalUnassigned: number;
  submissionsReceived: number;
  submissionsGraded: number;
  submissionsPending: number;
  solveRate: number; // percentage
  gradingRate: number; // percentage
  lessonsUploaded: number;
  lessonsVisible: number;
  lessonsHidden: number;
  lessonsValid: number;
  lessonsValidPercent: number;
  missingEvalRecords: string;
  missingLessonRecords: string;
  notes: string;
  category: 'top_overall' | 'top_aspect' | 'top_dept' | 'followup_pending' | 'followup_partial' | 'followup_no_eval';
  badges: string[];
  bestInDept?: string;
  rankInLessons?: number;
  rankInGrading?: number;
  adminRating?: 'ممتاز' | 'جيد جداً' | 'لا يوجد تعديل إداري';
  adminRatingBasis?: string;
  evalIndex?: number;
  lessonsIndex?: number;
  generalIndex?: number;
  hasActivityData: boolean;
}

export const SEPTEMBER_2026_LMS_METRICS = {
  date: '20 سبتمبر 2026',
  period: 'سبتمبر 2026',
  academicYear: '2026-2027',
  totalStaffCount: 61,
  teachersCount: 52, // داخل نطاق التقرير
  teachersWithActivity: 43,
  teachersWithoutActivity: 9,
  excludedCoordinatorsCount: 9,
  adminRatingsCount: 28, // 7 ممتاز + 21 جيد جداً
  adminRatingsExcellent: 7,
  adminRatingsVeryGood: 21,
  sectionsCount: 19,
  subjectSectionRecords: 188,
  evalCoveragePercent: 43.1, // 81 / 188
  evalCoveredRecords: 81,
  evalMissingRecords: 107,
  teachersCoverageFull: 14,
  teachersCoveragePartial: 9,
  teachersCoverageNone: 20,
  lessonsCoveragePercent: 82.4, // (188 - 33) / 188
  lessonsCoveredRecords: 155,
  zeroLessonRecords: 33,
  totalLessons: 1006,
  lessonsVisible: 581,
  lessonsVisiblePercent: 57.8,
  lessonsHidden: 425,
  lessonsHiddenPercent: 42.2,
  lessonsValid: 629,
  lessonsValidPercent: 62.5,
  totalSubmissions: 1119,
  gradedSubmissions: 875,
  gradingRate: 78.2,
  pendingSubmissions: 244,
  uploadedEvaluations: 147,
  assignedEvaluations: 124,
  unassignedEvaluations: 23,
  evalAssignmentRate: 84.4, // 124 / 147
  weightedSolveRate: 58.1, // 1119 / 1926
  potentialSubmissions: 1926,
};

export const GRADE_LEVEL_LMS_STATS = [
  { grade: 'الصف 7', evalPercent: 57.6, evalRatio: '19 / 33', lessonsPercent: 81.8, lessonsRatio: '27 / 33' },
  { grade: 'الصف 9', evalPercent: 39.4, evalRatio: '13 / 33', lessonsPercent: 81.8, lessonsRatio: '27 / 33' },
  { grade: 'الصف 10', evalPercent: 57.5, evalRatio: '23 / 40', lessonsPercent: 80.0, lessonsRatio: '32 / 40' },
  { grade: 'الصف 11', evalPercent: 42.1, evalRatio: '16 / 38', lessonsPercent: 86.8, lessonsRatio: '33 / 38' },
  { grade: 'الصف 12', evalPercent: 22.7, evalRatio: '10 / 44', lessonsPercent: 81.8, lessonsRatio: '36 / 44' },
];

export const TOP_10_INDEX_TEACHERS = [
  { rank: 1, name: 'ابراهيم حلمى ابراهيم جمعه', department: 'اللغة العربية', generalIndex: 95.00, evalIndex: 100.00, lessonsIndex: 90.00, sectionsCount: 3, adminRating: 'لا يوجد تعديل إداري' },
  { rank: 2, name: 'سيد مصطفى السيد سليمان', department: 'اللغة العربية', generalIndex: 94.35, evalIndex: 100.00, lessonsIndex: 88.70, sectionsCount: 4, adminRating: 'لا يوجد تعديل إداري' },
  { rank: 3, name: 'سمير بلفقي', department: 'اللغة العربية', generalIndex: 92.86, evalIndex: 100.00, lessonsIndex: 85.71, sectionsCount: 3, adminRating: 'لا يوجد تعديل إداري' },
  { rank: 4, name: 'محمد عادل عبدالعزيز الطاهر', department: 'اللغة العربية', generalIndex: 89.29, evalIndex: 90.00, lessonsIndex: 88.57, sectionsCount: 4, adminRating: 'لا يوجد تعديل إداري' },
  { rank: 5, name: 'ناصر احمد حسن حلوة', department: 'التربية الإسلامية', generalIndex: 85.57, evalIndex: 84.21, lessonsIndex: 86.94, sectionsCount: 6, adminRating: 'جيد جداً' },
  { rank: 6, name: 'الحسن علي محمد علي', department: 'التربية الإسلامية', generalIndex: 81.25, evalIndex: 100.00, lessonsIndex: 62.50, sectionsCount: 4, adminRating: 'لا يوجد تعديل إداري' },
  { rank: 7, name: 'عمران كاشف محمد حسين اسد', department: 'STEM', generalIndex: 80.00, evalIndex: 100.00, lessonsIndex: 60.00, sectionsCount: 1, adminRating: 'لا يوجد تعديل إداري' },
  { rank: 8, name: 'انس عبدالكريم موسى جرادات', department: 'مختبر الطاقة', generalIndex: 76.25, evalIndex: 92.50, lessonsIndex: 60.00, sectionsCount: 4, adminRating: 'ممتاز' },
  { rank: 9, name: 'خالد عصام بارودي', department: 'الحاسوب', generalIndex: 74.23, evalIndex: 88.46, lessonsIndex: 60.00, sectionsCount: 4, adminRating: 'لا يوجد تعديل إداري' },
  { rank: 10, name: 'امداد علي', department: 'الحاسوب', generalIndex: 74.00, evalIndex: 88.00, lessonsIndex: 60.00, sectionsCount: 2, adminRating: 'لا يوجد تعديل إداري' },
];

export const DEPARTMENT_PERFORMANCE_LIST = [
  { department: 'اللغة العربية', index: 88.55, evalCoverage: '68.4%', evalRatio: '13 / 19', lessonsCoverage: '100.0%', lessonsRatio: '19 / 19', recordsCount: 19, teachersRatio: '5 / 5', lessonsCount: 368, lessonsShare: '36.6%', evalsCount: 27, evalsShare: '18.4%', topTeacher: 'ابراهيم حلمي / سيد مصطفى / سمير بلفقي' },
  { department: 'التربية الإسلامية', index: 78.67, evalCoverage: '70.6%', evalRatio: '12 / 17', lessonsCoverage: '94.1%', lessonsRatio: '16 / 17', recordsCount: 17, teachersRatio: '4 / 4', lessonsCount: 96, lessonsShare: '9.5%', evalsCount: 32, evalsShare: '21.8%', topTeacher: 'الحسن علي محمد علي' },
  { department: 'مختبر الطاقة', index: 76.25, evalCoverage: '100.0%', evalRatio: '4 / 4', lessonsCoverage: '100.0%', lessonsRatio: '4 / 4', recordsCount: 4, teachersRatio: '1 / 2', lessonsCount: 5, lessonsShare: '0.5%', evalsCount: 4, evalsShare: '2.7%', topTeacher: 'انس عبدالكريم موسى جرادات' },
  { department: 'الدراسات الاجتماعية', index: 72.00, evalCoverage: '100.0%', evalRatio: '6 / 6', lessonsCoverage: '100.0%', lessonsRatio: '6 / 6', recordsCount: 6, teachersRatio: '1 / 1', lessonsCount: 30, lessonsShare: '3.0%', evalsCount: 9, evalsShare: '6.1%', topTeacher: 'فيصل محمد مسلم الحضري' },
  { department: 'الحاسوب', index: 65.13, evalCoverage: '70.6%', evalRatio: '12 / 17', lessonsCoverage: '100.0%', lessonsRatio: '17 / 17', recordsCount: 17, teachersRatio: '4 / 4', lessonsCount: 21, lessonsShare: '2.1%', evalsCount: 20, evalsShare: '13.6%', topTeacher: 'خالد عصام بارودي' },
  { department: 'مختبر التصنيع الرقمي', index: 59.90, evalCoverage: '87.5%', evalRatio: '7 / 8', lessonsCoverage: '100.0%', lessonsRatio: '8 / 8', recordsCount: 8, teachersRatio: '2 / 2', lessonsCount: 17, lessonsShare: '1.7%', evalsCount: 16, evalsShare: '10.9%', topTeacher: 'اياد أحمد سلمان عبدالقادر' },
  { department: 'STEM', index: 57.99, evalCoverage: '32.4%', evalRatio: '12 / 37', lessonsCoverage: '91.9%', lessonsRatio: '34 / 37', recordsCount: 37, teachersRatio: '12 / 17', lessonsCount: 120, lessonsShare: '11.9%', evalsCount: 24, evalsShare: '16.3%', topTeacher: 'عمران كاشف محمد حسين اسد' },
  { department: 'اللغة الإنجليزية', index: 57.49, evalCoverage: '21.1%', evalRatio: '4 / 19', lessonsCoverage: '100.0%', lessonsRatio: '19 / 19', recordsCount: 19, teachersRatio: '3 / 4', lessonsCount: 203, lessonsShare: '20.2%', evalsCount: 4, evalsShare: '2.7%', topTeacher: 'محمد سيد ميردادي' },
  { department: 'التصميم التكنولوجي', index: 43.11, evalCoverage: '45.8%', evalRatio: '11 / 24', lessonsCoverage: '58.3%', lessonsRatio: '14 / 24', recordsCount: 24, teachersRatio: '2 / 2', lessonsCount: 86, lessonsShare: '8.5%', evalsCount: 11, evalsShare: '7.5%', topTeacher: 'محمد شفاتا احمد / احمد المعاني' },
  { department: 'الرياضيات', index: null, evalCoverage: '0.0%', evalRatio: '0 / 18', lessonsCoverage: '100.0%', lessonsRatio: '18 / 18', recordsCount: 18, teachersRatio: '6 / 6', lessonsCount: 60, lessonsShare: '6.0%', evalsCount: 0, evalsShare: '0.0%', topTeacher: 'جعفر ياشلي / عبدالغني عبيده' },
  { department: 'التربية البدنية', index: null, evalCoverage: '0.0%', evalRatio: '0 / 19', lessonsCoverage: '0.0%', lessonsRatio: '0 / 19', recordsCount: 19, teachersRatio: '3 / 3', lessonsCount: 0, lessonsShare: '0.0%', evalsCount: 0, evalsShare: '0.0%', topTeacher: 'طاهر الحلو / فتحي بلحاج' },
  { department: 'مختبر الروبوت', index: null, evalCoverage: 'غير متاح', evalRatio: '0 / 0', lessonsCoverage: 'غير متاح', lessonsRatio: '0 / 0', recordsCount: 0, teachersRatio: '0 / 2', lessonsCount: 0, lessonsShare: '0.0%', evalsCount: 0, evalsShare: '0.0%', topTeacher: 'اياد سالمه / محمود اقبال' },
];

export const ADMINISTRATIVE_RATINGS_LIST = [
  // 7 ممتاز للمهندسين والمختبرات
  { name: 'ابراهيم عونى عمر حسن النعيمى', department: 'مختبر الطاقة', rating: 'ممتاز', basis: 'تقدير إداري للمهندسين والمختبرات التخصصية', hasActivity: false },
  { name: 'انس عبدالكريم موسى جرادات', department: 'مختبر الطاقة', rating: 'ممتاز', basis: 'تقدير إداري للمهندسين والمختبرات التخصصية', hasActivity: true },
  { name: 'اياد أحمد سلمان عبدالقادر', department: 'مختبر التصنيع الرقمي', rating: 'ممتاز', basis: 'تقدير إداري للمهندسين والمختبرات التخصصية', hasActivity: true },
  { name: 'اياد محمود علي سالمه', department: 'مختبر الروبوت', rating: 'ممتاز', basis: 'تقدير إداري للمهندسين والمختبرات التخصصية', hasActivity: false },
  { name: 'عبدالعزيز محمد', department: 'المختبرات التخصصية', rating: 'ممتاز', basis: 'تقدير إداري للمهندسين والمختبرات التخصصية', hasActivity: true },
  { name: 'على سالم على سالمين الصيعري', department: 'مختبر التصنيع الرقمي', rating: 'ممتاز', basis: 'تقدير إداري للمهندسين والمختبرات التخصصية', hasActivity: true },
  { name: 'محمود علم اقبال احمد', department: 'مختبر الروبوت', rating: 'ممتاز', basis: 'تقدير إداري للمهندسين والمختبرات التخصصية', hasActivity: false },

  // 21 جيد جداً
  { name: 'احمد اسامه صقر المعاني', department: 'التصميم التكنولوجي', rating: 'جيد جداً', basis: 'تقدير إداري لمعلمي مادة التصميم التكنولوجي وفق اعتماد الإدارة', hasActivity: true },
  { name: 'محمد شفاتا احمد', department: 'التصميم التكنولوجي', rating: 'جيد جداً', basis: 'تقدير إداري لمعلمي مادة التصميم التكنولوجي وفق اعتماد الإدارة', hasActivity: true },
  { name: 'اوزدن اوزغور', department: 'STEM', rating: 'جيد جداً', basis: 'تقدير إداري للمعلمين ضمن النطاق دون بيانات نشاط متاحة', hasActivity: false },
  { name: 'ايلفيس ايلوم تيتي', department: 'اللغة الإنجليزية', rating: 'جيد جداً', basis: 'تقدير إداري للمعلمين ضمن النطاق دون بيانات نشاط متاحة', hasActivity: false },
  { name: 'زايد كاظم', department: 'STEM', rating: 'جيد جداً', basis: 'تقدير إداري للمعلمين ضمن النطاق دون بيانات نشاط متاحة', hasActivity: false },
  { name: 'سليمان ميا', department: 'STEM', rating: 'جيد جداً', basis: 'تقدير إداري للمعلمين ضمن النطاق دون بيانات نشاط متاحة', hasActivity: false },
  { name: 'فوزي عصام بو فخرالدين', department: 'STEM', rating: 'جيد جداً', basis: 'تقدير إداري للمعلمين ضمن النطاق دون بيانات نشاط متاحة', hasActivity: false },
  { name: 'نبيل صالح الدين عطيه ايوب', department: 'STEM', rating: 'جيد جداً', basis: 'تقدير إداري للمعلمين ضمن النطاق دون بيانات نشاط متاحة', hasActivity: false },
  { name: 'حجيباهلل خاسييف', department: 'STEM', rating: 'جيد جداً', basis: 'حد أدنى إداري لمعلمي الصف الثاني عشر لاستخدام منصات تعليمية أخرى، وفق إفادة الإدارة', hasActivity: true },
  { name: 'زكي أحمد خالد', department: 'STEM', rating: 'جيد جداً', basis: 'حد أدنى إداري لمعلمي الصف الثاني عشر لاستخدام منصات تعليمية أخرى، وفق إفادة الإدارة', hasActivity: true },
  { name: 'زوكير عبدالرحمانوف', department: 'STEM', rating: 'جيد جداً', basis: 'حد أدنى إداري لمعلمي الصف الثاني عشر لاستخدام منصات تعليمية أخرى، وفق إفادة الإدارة', hasActivity: true },
  { name: 'سيد علي هايدور', department: 'STEM', rating: 'جيد جداً', basis: 'حد أدنى إداري لمعلمي الصف الثاني عشر لاستخدام منصات تعليمية أخرى، وفق إفادة الإدارة', hasActivity: true },
  { name: 'شاكيل احمد رفيق', department: 'STEM', rating: 'جيد جداً', basis: 'حد أدنى إداري لمعلمي الصف الثاني عشر لاستخدام منصات تعليمية أخرى، وفق إفادة الإدارة', hasActivity: true },
  { name: 'طاهر كمال عبدهللا الحلو', department: 'التربية البدنية', rating: 'جيد جداً', basis: 'حد أدنى إداري لمعلمي الصف الثاني عشر لاستخدام منصات تعليمية أخرى، وفق إفادة الإدارة', hasActivity: true },
  { name: 'عبدالغني عبيده', department: 'الرياضيات', rating: 'جيد جداً', basis: 'حد أدنى إداري لمعلمي الصف الثاني عشر لاستخدام منصات تعليمية أخرى، وفق إفادة الإدارة', hasActivity: true },
  { name: 'عالء حسني محمد موسى', department: 'التربية الإسلامية', rating: 'جيد جداً', basis: 'حد أدنى إداري لمعلمي الصف الثاني عشر لاستخدام منصات تعليمية أخرى، وفق إفادة الإدارة', hasActivity: true },
  { name: 'كريم ولجي', department: 'STEM', rating: 'جيد جداً', basis: 'حد أدنى إداري لمعلمي الصف الثاني عشر لاستخدام منصات تعليمية أخرى، وفق إفادة الإدارة', hasActivity: true },
  { name: 'محمد كمال محمد زيد', department: 'الرياضيات', rating: 'جيد جداً', basis: 'حد أدنى إداري لمعلمي الصف الثاني عشر لاستخدام منصات تعليمية أخرى، وفق إفادة الإدارة', hasActivity: true },
  { name: 'ناصر احمد حسن حلوة', department: 'التربية الإسلامية', rating: 'جيد جداً', basis: 'حد أدنى إداري لمعلمي الصف الثاني عشر لاستخدام منصات تعليمية أخرى، وفق إفادة الإدارة', hasActivity: true },
  { name: 'نزار بن عبدهللا حاجي', department: 'STEM', rating: 'جيد جداً', basis: 'حد أدنى إداري لمعلمي الصف الثاني عشر لاستخدام منصات تعليمية أخرى، وفق إفادة الإدارة', hasActivity: true },
  { name: 'هشام محمد امام سليمان', department: 'اللغة العربية', rating: 'جيد جداً', basis: 'حد أدنى إداري لمعلمي الصف الثاني عشر لاستخدام منصات تعليمية أخرى، وفق إفادة الإدارة', hasActivity: true },
];

export const EXCLUDED_COORDINATORS_LIST = [
  { name: 'احمد عادل عبده طبيشات', department: 'التعليم الإلكتروني', role: 'منسق المشاريع الالكترونية', reason: 'منسق مشاريع' },
  { name: 'احمد عقله فارس فارس', department: 'STEM', role: 'منسق STEM', reason: 'منسق قسم' },
  { name: 'اسعد محمود ناعس', department: 'اللغة العربية', role: 'منسق اللغة العربية', reason: 'منسق قسم' },
  { name: 'جاد مصطفى العيتاني', department: 'البحث العلمي', role: 'اخصائي البحث العلمي', reason: 'أخصائي بحث علمي' },
  { name: 'روي جورج مخول', department: 'الحاسوب', role: 'منسق الحاسوب', reason: 'منسق قسم' },
  { name: 'ماهر عيسى حسن علوان', department: 'التربية الإسلامية', role: 'منسق الدراسات الاسلامية', reason: 'منسق قسم' },
  { name: 'محمد عمر محمد سلامة', department: 'اللغة الإنجليزية', role: 'منسق اللغة الانجليزية', reason: 'منسق قسم' },
  { name: 'يامن فايز فرح', department: 'الرياضيات', role: 'منسق الرياضيات', reason: 'منسق قسم' },
  { name: 'يوسف محمد دحمان', department: 'التربية البدنية', role: 'منسق التربية البدنية', reason: 'منسق قسم' },
];

export const SEPTEMBER_2026_LMS_TEACHERS: LmsReportTeacherRecord[] = [
  {
    "id": "lms_t1",
    "name": "ابراهيم حلمى ابراهيم جمعه",
    "department": "اللغة العربية",
    "sectionsCount": 3,
    "subjectsAndSections": "اللغة العربية7 / 3 ،7 / 2 ،7 / 1 :",
    "evalCoverageRatio": "3/3",
    "evalCoveragePercent": 100.0,
    "evalUploaded": 9,
    "evalAssigned": 9,
    "evalUnassigned": 0,
    "submissionsReceived": 122,
    "submissionsGraded": 122,
    "submissionsPending": 0,
    "solveRate": 84.7,
    "gradingRate": 100.0,
    "lessonsUploaded": 66,
    "lessonsVisible": 33,
    "lessonsHidden": 33,
    "lessonsValid": 66,
    "lessonsValidPercent": 100.0,
    "missingEvalRecords": "ال يوجد",
    "missingLessonRecords": "ال يوجد",
    "notes": "تغطية تقييمات كاملة متميز في المؤشرات المشتركة المحددة في التقرير .جميع التسليمات المسجلة مصححة .جميع الدروس محسوبة وفق شروط المصدر .مراجعة جدولة إظهار  33درًسا مخفًيا؛ اإلخفاء وحده ال يثبت تقصيًر ا.",
    "category": "top_overall",
    "badges": [
      "المركز 1 في المؤشر العام 🏆",
      "تصحيح 100% (122/122)",
      "تغطية تقييمات كاملة 100%",
      "66 درساً مسجلاً"
    ],
    "adminRating": "لا يوجد تعديل إداري",
    "adminRatingBasis": "",
    "hasActivityData": true,
    "generalIndex": 95.0,
    "evalIndex": 100.0,
    "lessonsIndex": 90.0
  },
  {
    "id": "lms_t2",
    "name": "احمد اسامه صقر المعاني",
    "department": "التصميم التكنولوجي",
    "sectionsCount": 21,
    "subjectsAndSections": "البحث واالبتكار11 / 4 ،11 / 3 ،11 / 2 ،11 / 1 ،10 / 4 ،10 / 3 ،10 / 2 ،10 / 1 ،9 / 3 ،9 / 2 ،9 / 1 ،7 / 3 ،7 / 2 ،7 / 1 :؛ تكنولوجيا التصميم10 / 4 ،10 / 3 ،10 / 2 ،10 / 1 ،9 / 3 ،9 / 2 ،9 / 1 :",
    "evalCoverageRatio": "8/21",
    "evalCoveragePercent": 38.1,
    "evalUploaded": 8,
    "evalAssigned": 8,
    "evalUnassigned": 0,
    "submissionsReceived": 13,
    "submissionsGraded": 0,
    "submissionsPending": 13,
    "solveRate": 10.5,
    "gradingRate": 0.0,
    "lessonsUploaded": 74,
    "lessonsVisible": 74,
    "lessonsHidden": 0,
    "lessonsValid": 0,
    "lessonsValidPercent": 0.0,
    "missingEvalRecords": "البحث واالبتكار9 / 3 ،9 / 2 ،9 / 1 ،7 / 3 ،7 / 2 ،7 / 1 :؛ تكنولوجيا التصميم10 / 4 ،10 / 3 ،10 / 2 ،10 / 1 ،9 / 3 ،9 / 2 ،9 / 1 :",
    "missingLessonRecords": "البحث واالبتكار9 / 3 ،9 / 2 ،9 / 1 ،7 / 3 ،7 / 2 ،7 / 1 :؛ تكنولوجيا التصميم10 / 4 ،10 / 3 ،10 / 2 ،10 / 1 :",
    "notes": "8/ الدروس والتقييمات :جيد جًدا التقدير المعتمد :جيد جًدا في الدروس وجيد جًدا في التقييمات .تقدير إداري لمعلمي مادة التصميم التكنولوجي وفق اعتماد اإلدارة .المالحظات التالية تخص بيانات منصة قطر فقط .تغطية جزئية؛  13سجاًل غير ظاهر في ملف التقييمات. استكمال تصحيح  13تسليًما .نسبة الحل أقل من ٪50؛ متابعة مشاركة الطالب في التقييمات المسندة .استكمال الدروس في  10سجاًل  .مراجعة استيفاء الدروس لألقسام والمالحظات ونتاجات التعلم وفق شروط المصدر.",
    "category": "followup_pending",
    "badges": [
      "التقدير المعتمد: جيد جداً 🎖️",
      "13 تسليم بانتظار التصحيح ⏳",
      "تغطية تقييمات جزئية 38.1%",
      "74 درساً مسجلاً"
    ],
    "adminRating": "جيد جداً",
    "adminRatingBasis": "تقدير إداري لمعلمي مادة التصميم التكنولوجي وفق اعتماد الإدارة",
    "hasActivityData": true
  },
  {
    "id": "lms_t3",
    "name": "اشرف صالح محمد فدعوس",
    "department": "STEM",
    "sectionsCount": 2,
    "subjectsAndSections": "الفيزياء 11 / 2 ،11 / 1 :AP 1",
    "evalCoverageRatio": "0/2",
    "evalCoveragePercent": 0.0,
    "evalUploaded": 0,
    "evalAssigned": 0,
    "evalUnassigned": 0,
    "submissionsReceived": 0,
    "submissionsGraded": 0,
    "submissionsPending": 0,
    "solveRate": 0.0,
    "gradingRate": 0.0,
    "lessonsUploaded": 6,
    "lessonsVisible": 6,
    "lessonsHidden": 0,
    "lessonsValid": 0,
    "lessonsValidPercent": 0.0,
    "missingEvalRecords": "الفيزياء 11 / 2 ،11 / 1 :AP 1",
    "missingLessonRecords": "ال يوجد",
    "notes": "— ال يظهر سجل تقييم ال تظهر سجالت تقييم؛ يلزم التحقق من الرفع ومتطلبات المادة .مراجعة استيفاء الدروس لألقسام والمالحظات ونتاجات التعلم وفق شروط المصدر.",
    "category": "followup_no_eval",
    "badges": [
      "لا توجد تقييمات مسجلة",
      "6 درساً مسجلاً"
    ],
    "adminRating": "لا يوجد تعديل إداري",
    "adminRatingBasis": "",
    "hasActivityData": true
  },
  {
    "id": "lms_t4",
    "name": "الحسن علي محمد علي",
    "department": "التربية الإسلامية",
    "sectionsCount": 4,
    "subjectsAndSections": "التربية االسالمية11 / 1 ،7 / 3 ،7 / 2 ،7 / 1 :",
    "evalCoverageRatio": "4/4",
    "evalCoveragePercent": 100.0,
    "evalUploaded": 7,
    "evalAssigned": 7,
    "evalUnassigned": 0,
    "submissionsReceived": 86,
    "submissionsGraded": 86,
    "submissionsPending": 0,
    "solveRate": 76.8,
    "gradingRate": 100.0,
    "lessonsUploaded": 16,
    "lessonsVisible": 16,
    "lessonsHidden": 0,
    "lessonsValid": 1,
    "lessonsValidPercent": 6.2,
    "missingEvalRecords": "ال يوجد",
    "missingLessonRecords": "ال يوجد",
    "notes": "تغطية تقييمات كاملة تغطية رفع التقييمات كاملة في السجالت المتاحة .جميع التسليمات المسجلة مصححة .مراجعة استيفاء الدروس لألقسام والمالحظات ونتاجات التعلم وفق شروط المصدر.",
    "category": "top_overall",
    "badges": [
      "المركز 6 في المؤشر العام 🏆",
      "تصحيح 100% (86/86)",
      "تغطية تقييمات كاملة 100%",
      "16 درساً مسجلاً"
    ],
    "adminRating": "لا يوجد تعديل إداري",
    "adminRatingBasis": "",
    "hasActivityData": true,
    "generalIndex": 81.25,
    "evalIndex": 100.0,
    "lessonsIndex": 62.5
  },
  {
    "id": "lms_t5",
    "name": "امجد سهيل عزيز",
    "department": "STEM",
    "sectionsCount": 4,
    "subjectsAndSections": "10 / 4 ،10 / 3 ،10 / 2 ،10 / 1 :STEM",
    "evalCoverageRatio": "4/4",
    "evalCoveragePercent": 100.0,
    "evalUploaded": 12,
    "evalAssigned": 7,
    "evalUnassigned": 5,
    "submissionsReceived": 90,
    "submissionsGraded": 52,
    "submissionsPending": 38,
    "solveRate": 80.4,
    "gradingRate": 57.8,
    "lessonsUploaded": 12,
    "lessonsVisible": 12,
    "lessonsHidden": 0,
    "lessonsValid": 0,
    "lessonsValidPercent": 0.0,
    "missingEvalRecords": "ال يوجد",
    "missingLessonRecords": "ال يوجد",
    "notes": "تغطية تقييمات كاملة تغطية رفع التقييمات كاملة في السجالت المتاحة .إسناد  5تقييًما غير مسند .استكمال تصحيح  38تسليًما .مراجعة استيفاء الدروس لألقسام والمالحظات ونتاجات التعلم وفق شروط المصدر.",
    "category": "followup_pending",
    "badges": [
      "38 تسليم بانتظار التصحيح ⏳",
      "تغطية تقييمات كاملة 100%",
      "12 درساً مسجلاً"
    ],
    "adminRating": "لا يوجد تعديل إداري",
    "adminRatingBasis": "",
    "hasActivityData": true
  },
  {
    "id": "lms_t6",
    "name": "امداد علي",
    "department": "الحاسوب",
    "sectionsCount": 2,
    "subjectsAndSections": "علم الحاسوب9 / 2 ،9 / 1 :",
    "evalCoverageRatio": "2/2",
    "evalCoveragePercent": 100.0,
    "evalUploaded": 6,
    "evalAssigned": 4,
    "evalUnassigned": 2,
    "submissionsReceived": 30,
    "submissionsGraded": 28,
    "submissionsPending": 2,
    "solveRate": 46.9,
    "gradingRate": 93.3,
    "lessonsUploaded": 2,
    "lessonsVisible": 2,
    "lessonsHidden": 0,
    "lessonsValid": 0,
    "lessonsValidPercent": 0.0,
    "missingEvalRecords": "ال يوجد",
    "missingLessonRecords": "ال يوجد",
    "notes": "تغطية تقييمات كاملة تغطية رفع التقييمات كاملة في السجالت المتاحة .إسناد  2تقييًما غير مسند .استكمال تصحيح  2تسليًما .نسبة الحل أقل من ٪50؛ متابعة مشاركة الطالب في التقييمات المسندة .مراجعة استيفاء الدروس لألقسام والمالحظات ونتاجات التعلم وفق شروط المصدر.",
    "category": "top_overall",
    "badges": [
      "المركز 10 في المؤشر العام 🏆",
      "2 تسليم بانتظار التصحيح ⏳",
      "تغطية تقييمات كاملة 100%",
      "2 درساً مسجلاً"
    ],
    "adminRating": "لا يوجد تعديل إداري",
    "adminRatingBasis": "",
    "hasActivityData": true,
    "generalIndex": 74.0,
    "evalIndex": 88.0,
    "lessonsIndex": 60.0
  },
  {
    "id": "lms_t7",
    "name": "انس عبدالكريم موسى جرادات",
    "department": "مختبر الطاقة",
    "sectionsCount": 4,
    "subjectsAndSections": "المختبرات التخصصية10 / 3 ،7 / 3 ،7 / 2 ،7 / 1 :",
    "evalCoverageRatio": "4/4",
    "evalCoveragePercent": 100.0,
    "evalUploaded": 4,
    "evalAssigned": 4,
    "evalUnassigned": 0,
    "submissionsReceived": 8,
    "submissionsGraded": 6,
    "submissionsPending": 2,
    "solveRate": 12.5,
    "gradingRate": 75.0,
    "lessonsUploaded": 5,
    "lessonsVisible": 5,
    "lessonsHidden": 0,
    "lessonsValid": 0,
    "lessonsValidPercent": 0.0,
    "missingEvalRecords": "ال يوجد",
    "missingLessonRecords": "ال يوجد",
    "notes": "الدروس والتقييمات :ممتاز التقدير المعتمد :ممتاز في الدروس وممتاز في التقييمات .تقدير إداري للمهندسين والمختبرات التخصصية .المالحظات التالية تخص بيانات منصة قطر فقط .تغطية رفع التقييمات كاملة في السجالت المتاحة .استكمال تصحيح  2تسليًما. نسبة الحل أقل من ٪50؛ متابعة مشاركة الطالب في التقييمات المسندة .مراجعة استيفاء الدروس لألقسام والمالحظات ونتاجات التعلم وفق شروط المصدر.",
    "category": "top_overall",
    "badges": [
      "المركز 8 في المؤشر العام 🏆",
      "التقدير المعتمد: ممتاز 🎖️",
      "2 تسليم بانتظار التصحيح ⏳",
      "تغطية تقييمات كاملة 100%",
      "5 درساً مسجلاً"
    ],
    "adminRating": "ممتاز",
    "adminRatingBasis": "تقدير إداري للمهندسين والمختبرات التخصصية",
    "hasActivityData": true,
    "generalIndex": 76.25,
    "evalIndex": 92.5,
    "lessonsIndex": 60.0
  },
  {
    "id": "lms_t8",
    "name": "اياد أحمد سلمان عبدالقادر",
    "department": "مختبر التصنيع الرقمي",
    "sectionsCount": 3,
    "subjectsAndSections": "المختبرات التخصصية11 / 1 ،10 / 2 ،10 / 1 :",
    "evalCoverageRatio": "3/3",
    "evalCoveragePercent": 100.0,
    "evalUploaded": 6,
    "evalAssigned": 6,
    "evalUnassigned": 0,
    "submissionsReceived": 30,
    "submissionsGraded": 0,
    "submissionsPending": 30,
    "solveRate": 31.2,
    "gradingRate": 0.0,
    "lessonsUploaded": 7,
    "lessonsVisible": 7,
    "lessonsHidden": 0,
    "lessonsValid": 0,
    "lessonsValidPercent": 0.0,
    "missingEvalRecords": "ال يوجد",
    "missingLessonRecords": "ال يوجد",
    "notes": "الدروس والتقييمات :ممتاز التقدير المعتمد :ممتاز في الدروس وممتاز في التقييمات .تقدير إداري للمهندسين والمختبرات التخصصية .المالحظات التالية تخص بيانات منصة قطر فقط .تغطية رفع التقييمات كاملة في السجالت المتاحة .استكمال تصحيح  30تسليًما. نسبة الحل أقل من ٪50؛ متابعة مشاركة الطالب في التقييمات المسندة .مراجعة استيفاء الدروس لألقسام والمالحظات ونتاجات التعلم وفق شروط المصدر.",
    "category": "followup_pending",
    "badges": [
      "التقدير المعتمد: ممتاز 🎖️",
      "30 تسليم بانتظار التصحيح ⏳",
      "تغطية تقييمات كاملة 100%",
      "7 درساً مسجلاً"
    ],
    "adminRating": "ممتاز",
    "adminRatingBasis": "تقدير إداري للمهندسين والمختبرات التخصصية",
    "hasActivityData": true
  },
  {
    "id": "lms_t9",
    "name": "جعفر ياشلي",
    "department": "الرياضيات",
    "sectionsCount": 3,
    "subjectsAndSections": "الرياضيات10 / 3 ،9 / 3 ،9 / 2 :",
    "evalCoverageRatio": "0/3",
    "evalCoveragePercent": 0.0,
    "evalUploaded": 0,
    "evalAssigned": 0,
    "evalUnassigned": 0,
    "submissionsReceived": 0,
    "submissionsGraded": 0,
    "submissionsPending": 0,
    "solveRate": 0.0,
    "gradingRate": 0.0,
    "lessonsUploaded": 9,
    "lessonsVisible": 9,
    "lessonsHidden": 0,
    "lessonsValid": 0,
    "lessonsValidPercent": 0.0,
    "missingEvalRecords": "الرياضيات10 / 3 ،9 / 3 ،9 / 2 :",
    "missingLessonRecords": "ال يوجد",
    "notes": "— ال يظهر سجل تقييم ال تظهر سجالت تقييم؛ يلزم التحقق من الرفع ومتطلبات المادة .مراجعة استيفاء الدروس لألقسام والمالحظات ونتاجات التعلم وفق شروط المصدر.",
    "category": "followup_no_eval",
    "badges": [
      "لا توجد تقييمات مسجلة",
      "9 درساً مسجلاً"
    ],
    "adminRating": "لا يوجد تعديل إداري",
    "adminRatingBasis": "",
    "hasActivityData": true
  },
  {
    "id": "lms_t10",
    "name": "حجيباهلل خاسييف",
    "department": "STEM",
    "sectionsCount": 5,
    "subjectsAndSections": "الكيمياء11 / 4 ،11 / 3 ،11 / 2 ،11 / 1 :؛ الكيمياء 12 / 2 :AP",
    "evalCoverageRatio": "0/5",
    "evalCoveragePercent": 0.0,
    "evalUploaded": 0,
    "evalAssigned": 0,
    "evalUnassigned": 0,
    "submissionsReceived": 0,
    "submissionsGraded": 0,
    "submissionsPending": 0,
    "solveRate": 0.0,
    "gradingRate": 0.0,
    "lessonsUploaded": 47,
    "lessonsVisible": 7,
    "lessonsHidden": 40,
    "lessonsValid": 40,
    "lessonsValidPercent": 85.1,
    "missingEvalRecords": "الكيمياء11 / 4 ،11 / 3 ،11 / 2 ،11 / 1 :؛ الكيمياء 12 / 2 :AP",
    "missingLessonRecords": "ال يوجد",
    "notes": "— الدروس والتقييمات :جيد جًدا التقدير المعتمد :جيد جًدا في الدروس وجيد جًدا في التقييمات .حد أدنى إداري لمعلمي الصف الثاني عشر الستخدام منصات تعليمية أخرى ،وفق إفادة اإلدارة .المالحظات التالية تخص بيانات منصة قطر فقط .ال تظهر سجالت تقييم؛ يلزم التحقق من الرفع ومتطلبات المادة .مراجعة استيفاء الدروس لألقسام والمالحظات ونتاجات التعلم وفق شروط المصدر .مراجعة جدولة إظهار  40درًسا مخفًيا؛ اإلخفاء وحده ال يثبت تقصيًر ا.",
    "category": "followup_no_eval",
    "badges": [
      "التقدير المعتمد: جيد جداً 🎖️",
      "لا توجد تقييمات مسجلة",
      "47 درساً مسجلاً"
    ],
    "adminRating": "جيد جداً",
    "adminRatingBasis": "حد أدنى إداري لمعلمي الصف الثاني عشر لاستخدام منصات تعليمية أخرى، وفق إفادة الإدارة",
    "hasActivityData": true
  },
  {
    "id": "lms_t11",
    "name": "حسام حامد علي البنوي",
    "department": "التربية الإسلامية",
    "sectionsCount": 4,
    "subjectsAndSections": "التربية االسالمية11 / 2 ،9 / 3 ،9 / 2 ،9 / 1 :",
    "evalCoverageRatio": "0/4",
    "evalCoveragePercent": 0.0,
    "evalUploaded": 0,
    "evalAssigned": 0,
    "evalUnassigned": 0,
    "submissionsReceived": 0,
    "submissionsGraded": 0,
    "submissionsPending": 0,
    "solveRate": 0.0,
    "gradingRate": 0.0,
    "lessonsUploaded": 17,
    "lessonsVisible": 17,
    "lessonsHidden": 0,
    "lessonsValid": 14,
    "lessonsValidPercent": 82.4,
    "missingEvalRecords": "التربية االسالمية11 / 2 ،9 / 3 ،9 / 2 ،9 / 1 :",
    "missingLessonRecords": "ال يوجد",
    "notes": "— ال يظهر سجل تقييم ال تظهر سجالت تقييم؛ يلزم التحقق من الرفع ومتطلبات المادة .مراجعة استيفاء الدروس لألقسام والمالحظات ونتاجات التعلم وفق شروط المصدر.",
    "category": "followup_no_eval",
    "badges": [
      "لا توجد تقييمات مسجلة",
      "17 درساً مسجلاً"
    ],
    "adminRating": "لا يوجد تعديل إداري",
    "adminRatingBasis": "",
    "hasActivityData": true
  },
  {
    "id": "lms_t12",
    "name": "خالد عصام بارودي",
    "department": "الحاسوب",
    "sectionsCount": 4,
    "subjectsAndSections": "علم الحاسوب10 / 3 ،10 / 2 ،10 / 1 ،9 / 3 :",
    "evalCoverageRatio": "4/4",
    "evalCoveragePercent": 100.0,
    "evalUploaded": 6,
    "evalAssigned": 6,
    "evalUnassigned": 0,
    "submissionsReceived": 39,
    "submissionsGraded": 24,
    "submissionsPending": 15,
    "solveRate": 40.6,
    "gradingRate": 61.5,
    "lessonsUploaded": 4,
    "lessonsVisible": 4,
    "lessonsHidden": 0,
    "lessonsValid": 0,
    "lessonsValidPercent": 0.0,
    "missingEvalRecords": "ال يوجد",
    "missingLessonRecords": "ال يوجد",
    "notes": "تغطية تقييمات كاملة تغطية رفع التقييمات كاملة في السجالت المتاحة .استكمال تصحيح  15تسليًما .نسبة الحل أقل من ٪50؛ متابعة مشاركة الطالب في التقييمات المسندة .مراجعة استيفاء الدروس لألقسام والمالحظات ونتاجات التعلم وفق شروط المصدر.",
    "category": "top_overall",
    "badges": [
      "المركز 9 في المؤشر العام 🏆",
      "15 تسليم بانتظار التصحيح ⏳",
      "تغطية تقييمات كاملة 100%",
      "4 درساً مسجلاً"
    ],
    "adminRating": "لا يوجد تعديل إداري",
    "adminRatingBasis": "",
    "hasActivityData": true,
    "generalIndex": 74.23,
    "evalIndex": 88.46,
    "lessonsIndex": 60.0
  },
  {
    "id": "lms_t13",
    "name": "راجي ترابي",
    "department": "STEM",
    "sectionsCount": 3,
    "subjectsAndSections": "9 / 1 ،7 / 2 ،7 / 1 :STEM",
    "evalCoverageRatio": "1/3",
    "evalCoveragePercent": 33.3,
    "evalUploaded": 1,
    "evalAssigned": 1,
    "evalUnassigned": 0,
    "submissionsReceived": 15,
    "submissionsGraded": 15,
    "submissionsPending": 0,
    "solveRate": 93.8,
    "gradingRate": 100.0,
    "lessonsUploaded": 8,
    "lessonsVisible": 8,
    "lessonsHidden": 0,
    "lessonsValid": 0,
    "lessonsValidPercent": 0.0,
    "missingEvalRecords": "9 / 1 ،7 / 1 :STEM",
    "missingLessonRecords": "ال يوجد",
    "notes": "تغطية تقييمات جزئية تغطية جزئية؛  2سجاًل غير ظاهر في ملف التقييمات .جميع التسليمات المسجلة مصححة .مراجعة استيفاء الدروس لألقسام والمالحظات ونتاجات التعلم وفق شروط المصدر.",
    "category": "followup_partial",
    "badges": [
      "تصحيح 100% (15/15)",
      "تغطية تقييمات جزئية 33.3%",
      "8 درساً مسجلاً"
    ],
    "adminRating": "لا يوجد تعديل إداري",
    "adminRatingBasis": "",
    "hasActivityData": true
  },
  {
    "id": "lms_t14",
    "name": "زكي أحمد خالد",
    "department": "STEM",
    "sectionsCount": 5,
    "subjectsAndSections": "اللغة االنجليزية12 / 5 ،12 / 4 ،12 / 3 ،12 / 2 ،12 / 1 :",
    "evalCoverageRatio": "0/5",
    "evalCoveragePercent": 0.0,
    "evalUploaded": 0,
    "evalAssigned": 0,
    "evalUnassigned": 0,
    "submissionsReceived": 0,
    "submissionsGraded": 0,
    "submissionsPending": 0,
    "solveRate": 0.0,
    "gradingRate": 0.0,
    "lessonsUploaded": 5,
    "lessonsVisible": 5,
    "lessonsHidden": 0,
    "lessonsValid": 0,
    "lessonsValidPercent": 0.0,
    "missingEvalRecords": "اللغة االنجليزية12 / 5 ،12 / 4 ،12 / 3 ،12 / 2 ،12 / 1 :",
    "missingLessonRecords": "ال يوجد",
    "notes": "— الدروس والتقييمات :جيد جًدا التقدير المعتمد :جيد جًدا في الدروس وجيد جًدا في التقييمات .حد أدنى إداري لمعلمي الصف الثاني عشر الستخدام منصات تعليمية أخرى ،وفق إفادة اإلدارة .المالحظات التالية تخص بيانات منصة قطر فقط .ال تظهر سجالت تقييم؛ يلزم التحقق من الرفع ومتطلبات المادة .مراجعة استيفاء الدروس لألقسام والمالحظات ونتاجات التعلم وفق شروط المصدر.",
    "category": "followup_no_eval",
    "badges": [
      "التقدير المعتمد: جيد جداً 🎖️",
      "لا توجد تقييمات مسجلة",
      "5 درساً مسجلاً"
    ],
    "adminRating": "جيد جداً",
    "adminRatingBasis": "حد أدنى إداري لمعلمي الصف الثاني عشر لاستخدام منصات تعليمية أخرى، وفق إفادة الإدارة",
    "hasActivityData": true
  },
  {
    "id": "lms_t15",
    "name": "زوكير عبدالرحمانوف",
    "department": "STEM",
    "sectionsCount": 2,
    "subjectsAndSections": "فيزياء الميكانيكا 12 / 2 ،12 / 1 :C-AP",
    "evalCoverageRatio": "0/2",
    "evalCoveragePercent": 0.0,
    "evalUploaded": 0,
    "evalAssigned": 0,
    "evalUnassigned": 0,
    "submissionsReceived": 0,
    "submissionsGraded": 0,
    "submissionsPending": 0,
    "solveRate": 0.0,
    "gradingRate": 0.0,
    "lessonsUploaded": 4,
    "lessonsVisible": 4,
    "lessonsHidden": 0,
    "lessonsValid": 0,
    "lessonsValidPercent": 0.0,
    "missingEvalRecords": "فيزياء الميكانيكا 12 / 2 ،12 / 1 :C-AP",
    "missingLessonRecords": "ال يوجد",
    "notes": "— الدروس والتقييمات :جيد جًدا التقدير المعتمد :جيد جًدا في الدروس وجيد جًدا في التقييمات .حد أدنى إداري لمعلمي الصف الثاني عشر الستخدام منصات تعليمية أخرى ،وفق إفادة اإلدارة .المالحظات التالية تخص بيانات منصة قطر فقط .ال تظهر سجالت تقييم؛ يلزم التحقق من الرفع ومتطلبات المادة .مراجعة استيفاء الدروس لألقسام والمالحظات ونتاجات التعلم وفق شروط المصدر.",
    "category": "followup_no_eval",
    "badges": [
      "التقدير المعتمد: جيد جداً 🎖️",
      "لا توجد تقييمات مسجلة",
      "4 درساً مسجلاً"
    ],
    "adminRating": "جيد جداً",
    "adminRatingBasis": "حد أدنى إداري لمعلمي الصف الثاني عشر لاستخدام منصات تعليمية أخرى، وفق إفادة الإدارة",
    "hasActivityData": true
  },
  {
    "id": "lms_t16",
    "name": "سمير بلفقي",
    "department": "اللغة العربية",
    "sectionsCount": 3,
    "subjectsAndSections": "اللغة العربية9 / 3 ،9 / 2 ،9 / 1 :",
    "evalCoverageRatio": "3/3",
    "evalCoveragePercent": 100.0,
    "evalUploaded": 3,
    "evalAssigned": 3,
    "evalUnassigned": 0,
    "submissionsReceived": 47,
    "submissionsGraded": 47,
    "submissionsPending": 0,
    "solveRate": 97.9,
    "gradingRate": 100.0,
    "lessonsUploaded": 84,
    "lessonsVisible": 36,
    "lessonsHidden": 48,
    "lessonsValid": 78,
    "lessonsValidPercent": 92.9,
    "missingEvalRecords": "ال يوجد",
    "missingLessonRecords": "ال يوجد",
    "notes": "تغطية تقييمات كاملة متميز في المؤشرات المشتركة المحددة في التقرير .جميع التسليمات المسجلة مصححة .مراجعة استيفاء الدروس لألقسام والمالحظات ونتاجات التعلم وفق شروط المصدر .مراجعة جدولة إظهار  48درًسا مخفًيا؛ اإلخفاء وحده ال يثبت تقصيًر ا.",
    "category": "top_overall",
    "badges": [
      "المركز 3 في المؤشر العام 🏆",
      "تصحيح 100% (47/47)",
      "تغطية تقييمات كاملة 100%",
      "84 درساً مسجلاً"
    ],
    "adminRating": "لا يوجد تعديل إداري",
    "adminRatingBasis": "",
    "hasActivityData": true,
    "generalIndex": 92.86,
    "evalIndex": 100.0,
    "lessonsIndex": 85.71
  },
  {
    "id": "lms_t17",
    "name": "سيد علي هايدور",
    "department": "STEM",
    "sectionsCount": 2,
    "subjectsAndSections": "األحياء11 / 4 :؛ األحياء 12 / 4 :AP",
    "evalCoverageRatio": "2/2",
    "evalCoveragePercent": 100.0,
    "evalUploaded": 2,
    "evalAssigned": 2,
    "evalUnassigned": 0,
    "submissionsReceived": 25,
    "submissionsGraded": 0,
    "submissionsPending": 25,
    "solveRate": 100.0,
    "gradingRate": 0.0,
    "lessonsUploaded": 7,
    "lessonsVisible": 2,
    "lessonsHidden": 5,
    "lessonsValid": 5,
    "lessonsValidPercent": 71.4,
    "missingEvalRecords": "ال يوجد",
    "missingLessonRecords": "ال يوجد",
    "notes": "الدروس والتقييمات :جيد جًدا التقدير المعتمد :جيد جًدا في الدروس وجيد جًدا في التقييمات .حد أدنى إداري لمعلمي الصف الثاني عشر الستخدام منصات تعليمية أخرى ،وفق إفادة اإلدارة .المالحظات التالية تخص بيانات منصة قطر فقط .تغطية رفع التقييمات كاملة في السجالت المتاحة .استكمال تصحيح  25تسليًما .مراجعة استيفاء الدروس لألقسام والمالحظات ونتاجات التعلم وفق شروط المصدر .مراجعة جدولة إظهار  5درًسا مخفًيا؛ اإلخفاء وحده ال يثبت تقصيًر ا.",
    "category": "followup_pending",
    "badges": [
      "التقدير المعتمد: جيد جداً 🎖️",
      "25 تسليم بانتظار التصحيح ⏳",
      "تغطية تقييمات كاملة 100%",
      "7 درساً مسجلاً"
    ],
    "adminRating": "جيد جداً",
    "adminRatingBasis": "حد أدنى إداري لمعلمي الصف الثاني عشر لاستخدام منصات تعليمية أخرى، وفق إفادة الإدارة",
    "hasActivityData": true
  },
  {
    "id": "lms_t18",
    "name": "سيد مصطفى السيد سليمان",
    "department": "اللغة العربية",
    "sectionsCount": 4,
    "subjectsAndSections": "اللغة العربية10 / 4 ،10 / 3 ،10 / 2 ،10 / 1 :",
    "evalCoverageRatio": "4/4",
    "evalCoveragePercent": 100.0,
    "evalUploaded": 8,
    "evalAssigned": 8,
    "evalUnassigned": 0,
    "submissionsReceived": 119,
    "submissionsGraded": 119,
    "submissionsPending": 0,
    "solveRate": 93.0,
    "gradingRate": 100.0,
    "lessonsUploaded": 92,
    "lessonsVisible": 40,
    "lessonsHidden": 52,
    "lessonsValid": 92,
    "lessonsValidPercent": 100.0,
    "missingEvalRecords": "ال يوجد",
    "missingLessonRecords": "ال يوجد",
    "notes": "تغطية تقييمات كاملة متميز في المؤشرات المشتركة المحددة في التقرير .جميع التسليمات المسجلة مصححة .جميع الدروس محسوبة وفق شروط المصدر .مراجعة جدولة إظهار  52درًسا مخفًيا؛ اإلخفاء وحده ال يثبت تقصيًر ا.",
    "category": "top_overall",
    "badges": [
      "المركز 2 في المؤشر العام 🏆",
      "تصحيح 100% (119/119)",
      "تغطية تقييمات كاملة 100%",
      "92 درساً مسجلاً"
    ],
    "adminRating": "لا يوجد تعديل إداري",
    "adminRatingBasis": "",
    "hasActivityData": true,
    "generalIndex": 94.35,
    "evalIndex": 100.0,
    "lessonsIndex": 88.7
  },
  {
    "id": "lms_t19",
    "name": "شاكيل احمد رفيق",
    "department": "STEM",
    "sectionsCount": 4,
    "subjectsAndSections": "الكيمياء 12 / 5 ،12 / 4 ،12 / 3 ،12 / 1 :AP",
    "evalCoverageRatio": "0/4",
    "evalCoveragePercent": 0.0,
    "evalUploaded": 0,
    "evalAssigned": 0,
    "evalUnassigned": 0,
    "submissionsReceived": 0,
    "submissionsGraded": 0,
    "submissionsPending": 0,
    "solveRate": 0.0,
    "gradingRate": 0.0,
    "lessonsUploaded": 4,
    "lessonsVisible": 4,
    "lessonsHidden": 0,
    "lessonsValid": 0,
    "lessonsValidPercent": 0.0,
    "missingEvalRecords": "الكيمياء 12 / 5 ،12 / 4 ،12 / 3 ،12 / 1 :AP",
    "missingLessonRecords": "ال يوجد",
    "notes": "— الدروس والتقييمات :جيد جًدا التقدير المعتمد :جيد جًدا في الدروس وجيد جًدا في التقييمات .حد أدنى إداري لمعلمي الصف الثاني عشر الستخدام منصات تعليمية أخرى ،وفق إفادة اإلدارة .المالحظات التالية تخص بيانات منصة قطر فقط .ال تظهر سجالت تقييم؛ يلزم التحقق من الرفع ومتطلبات المادة .مراجعة استيفاء الدروس لألقسام والمالحظات ونتاجات التعلم وفق شروط المصدر.",
    "category": "followup_no_eval",
    "badges": [
      "التقدير المعتمد: جيد جداً 🎖️",
      "لا توجد تقييمات مسجلة",
      "4 درساً مسجلاً"
    ],
    "adminRating": "جيد جداً",
    "adminRatingBasis": "حد أدنى إداري لمعلمي الصف الثاني عشر لاستخدام منصات تعليمية أخرى، وفق إفادة الإدارة",
    "hasActivityData": true
  },
  {
    "id": "lms_t20",
    "name": "ضرار حسن صادق مالح",
    "department": "STEM",
    "sectionsCount": 2,
    "subjectsAndSections": "الفيزياء 11 / 4 ،11 / 3 :AP 1",
    "evalCoverageRatio": "0/2",
    "evalCoveragePercent": 0.0,
    "evalUploaded": 0,
    "evalAssigned": 0,
    "evalUnassigned": 0,
    "submissionsReceived": 0,
    "submissionsGraded": 0,
    "submissionsPending": 0,
    "solveRate": 0.0,
    "gradingRate": 0.0,
    "lessonsUploaded": 12,
    "lessonsVisible": 12,
    "lessonsHidden": 0,
    "lessonsValid": 0,
    "lessonsValidPercent": 0.0,
    "missingEvalRecords": "الفيزياء 11 / 4 ،11 / 3 :AP 1",
    "missingLessonRecords": "ال يوجد",
    "notes": "— ال يظهر سجل تقييم ال تظهر سجالت تقييم؛ يلزم التحقق من الرفع ومتطلبات المادة .مراجعة استيفاء الدروس لألقسام والمالحظات ونتاجات التعلم وفق شروط المصدر.",
    "category": "followup_no_eval",
    "badges": [
      "لا توجد تقييمات مسجلة",
      "12 درساً مسجلاً"
    ],
    "adminRating": "لا يوجد تعديل إداري",
    "adminRatingBasis": "",
    "hasActivityData": true
  },
  {
    "id": "lms_t21",
    "name": "طاهر كمال عبدهللا الحلو",
    "department": "التربية البدنية",
    "sectionsCount": 5,
    "subjectsAndSections": "التربية البدنية12 / 5 ،12 / 4 ،12 / 3 ،12 / 2 ،12 / 1 :",
    "evalCoverageRatio": "0/5",
    "evalCoveragePercent": 0.0,
    "evalUploaded": 0,
    "evalAssigned": 0,
    "evalUnassigned": 0,
    "submissionsReceived": 0,
    "submissionsGraded": 0,
    "submissionsPending": 0,
    "solveRate": 0.0,
    "gradingRate": 0.0,
    "lessonsUploaded": 0,
    "lessonsVisible": 0,
    "lessonsHidden": 0,
    "lessonsValid": 0,
    "lessonsValidPercent": 0.0,
    "missingEvalRecords": "التربية البدنية12 / 5 ،12 / 4 ،12 / 3 ،12 / 2 ،12 / 1 :",
    "missingLessonRecords": "التربية البدنية12 / 5 ،12 / 4 ،12 / 3 ،12 / 2 ،12 / 1 :",
    "notes": "— الدروس والتقييمات :جيد جًدا التقدير المعتمد :جيد جًدا في الدروس وجيد جًدا في التقييمات .حد أدنى إداري لمعلمي الصف الثاني عشر الستخدام منصات تعليمية أخرى ،وفق إفادة اإلدارة .المالحظات التالية تخص بيانات منصة قطر فقط .ال تظهر سجالت تقييم؛ يلزم التحقق من الرفع ومتطلبات المادة .استكمال الدروس في  5سجاًل .",
    "category": "followup_no_eval",
    "badges": [
      "التقدير المعتمد: جيد جداً 🎖️",
      "لا توجد تقييمات مسجلة"
    ],
    "adminRating": "جيد جداً",
    "adminRatingBasis": "حد أدنى إداري لمعلمي الصف الثاني عشر لاستخدام منصات تعليمية أخرى، وفق إفادة الإدارة",
    "hasActivityData": true
  },
  {
    "id": "lms_t22",
    "name": "عبدالعزيز محمد",
    "department": "المختبرات التخصصية",
    "sectionsCount": 7,
    "subjectsAndSections": "المختبرات التخصصية12 / 5 ،12 / 4 ،12 / 3 ،12 / 2 ،11 / 4 ،11 / 3 ،11 / 2 :",
    "evalCoverageRatio": "4/7",
    "evalCoveragePercent": 57.1,
    "evalUploaded": 8,
    "evalAssigned": 8,
    "evalUnassigned": 0,
    "submissionsReceived": 38,
    "submissionsGraded": 9,
    "submissionsPending": 29,
    "solveRate": 38.4,
    "gradingRate": 23.7,
    "lessonsUploaded": 13,
    "lessonsVisible": 13,
    "lessonsHidden": 0,
    "lessonsValid": 0,
    "lessonsValidPercent": 0.0,
    "missingEvalRecords": "المختبرات التخصصية12 / 4 ،11 / 4 ،11 / 2 :",
    "missingLessonRecords": "المختبرات التخصصية12 / 4 ،11 / 4 :",
    "notes": "الدروس والتقييمات :ممتاز التقدير المعتمد :ممتاز في الدروس وممتاز في التقييمات .تقدير إداري للمهندسين والمختبرات التخصصية .المالحظات التالية تخص بيانات منصة قطر فقط .تغطية جزئية؛  3سجاًل غير ظاهر في ملف التقييمات .استكمال تصحيح 29 تسليًما .نسبة الحل أقل من ٪50؛ متابعة مشاركة الطالب في التقييمات المسندة .استكمال الدروس في  2سجاًل  .مراجعة استيفاء الدروس لألقسام والمالحظات ونتاجات التعلم وفق شروط المصدر.",
    "category": "followup_pending",
    "badges": [
      "التقدير المعتمد: ممتاز 🎖️",
      "29 تسليم بانتظار التصحيح ⏳",
      "تغطية تقييمات جزئية 57.1%",
      "13 درساً مسجلاً"
    ],
    "adminRating": "ممتاز",
    "adminRatingBasis": "تقدير إداري للمهندسين والمختبرات التخصصية",
    "hasActivityData": true
  },
  {
    "id": "lms_t23",
    "name": "عبدالغني عبيده",
    "department": "الرياضيات",
    "sectionsCount": 3,
    "subjectsAndSections": "التفاضل والتكامل 12 / 2 ،12 / 1 :AP؛ التفاضل والتكامل التمهيدي 11 / 3 :AP",
    "evalCoverageRatio": "0/3",
    "evalCoveragePercent": 0.0,
    "evalUploaded": 0,
    "evalAssigned": 0,
    "evalUnassigned": 0,
    "submissionsReceived": 0,
    "submissionsGraded": 0,
    "submissionsPending": 0,
    "solveRate": 0.0,
    "gradingRate": 0.0,
    "lessonsUploaded": 3,
    "lessonsVisible": 3,
    "lessonsHidden": 0,
    "lessonsValid": 0,
    "lessonsValidPercent": 0.0,
    "missingEvalRecords": "التفاضل والتكامل 12 / 2 ،12 / 1 :AP؛ التفاضل والتكامل التمهيدي 11 / 3 :AP",
    "missingLessonRecords": "ال يوجد",
    "notes": "— الدروس والتقييمات :جيد جًدا التقدير المعتمد :جيد جًدا في الدروس وجيد جًدا في التقييمات .حد أدنى إداري لمعلمي الصف الثاني عشر الستخدام منصات تعليمية أخرى ،وفق إفادة اإلدارة .المالحظات التالية تخص بيانات منصة قطر فقط .ال تظهر سجالت تقييم؛ يلزم التحقق من الرفع ومتطلبات المادة .مراجعة استيفاء الدروس لألقسام والمالحظات ونتاجات التعلم وفق شروط المصدر.",
    "category": "followup_no_eval",
    "badges": [
      "التقدير المعتمد: جيد جداً 🎖️",
      "لا توجد تقييمات مسجلة",
      "3 درساً مسجلاً"
    ],
    "adminRating": "جيد جداً",
    "adminRatingBasis": "حد أدنى إداري لمعلمي الصف الثاني عشر لاستخدام منصات تعليمية أخرى، وفق إفادة الإدارة",
    "hasActivityData": true
  },
  {
    "id": "lms_t24",
    "name": "عالء حسني محمد موسى",
    "department": "التربية الإسلامية",
    "sectionsCount": 3,
    "subjectsAndSections": "التربية االسالمية12 / 5 ،10 / 4 ،10 / 3 :",
    "evalCoverageRatio": "2/3",
    "evalCoveragePercent": 66.7,
    "evalUploaded": 6,
    "evalAssigned": 6,
    "evalUnassigned": 0,
    "submissionsReceived": 64,
    "submissionsGraded": 64,
    "submissionsPending": 0,
    "solveRate": 66.7,
    "gradingRate": 100.0,
    "lessonsUploaded": 14,
    "lessonsVisible": 14,
    "lessonsHidden": 0,
    "lessonsValid": 2,
    "lessonsValidPercent": 14.3,
    "missingEvalRecords": "التربية االسالمية12 / 5 :",
    "missingLessonRecords": "التربية االسالمية12 / 5 :",
    "notes": "الدروس والتقييمات :جيد جًدا التقدير المعتمد :جيد جًدا في الدروس وجيد جًدا في التقييمات .حد أدنى إداري لمعلمي الصف الثاني عشر الستخدام منصات تعليمية أخرى ،وفق إفادة اإلدارة .المالحظات التالية تخص بيانات منصة قطر فقط .تغطية جزئية؛  1سجاًل غير ظاهر في ملف التقييمات .جميع التسليمات المسجلة مصححة .استكمال الدروس في  1سجاًل  .مراجعة استيفاء الدروس لألقسام والمالحظات ونتاجات التعلم وفق شروط المصدر.",
    "category": "followup_partial",
    "badges": [
      "التقدير المعتمد: جيد جداً 🎖️",
      "تصحيح 100% (64/64)",
      "تغطية تقييمات جزئية 66.7%",
      "14 درساً مسجلاً"
    ],
    "adminRating": "جيد جداً",
    "adminRatingBasis": "حد أدنى إداري لمعلمي الصف الثاني عشر لاستخدام منصات تعليمية أخرى، وفق إفادة الإدارة",
    "hasActivityData": true
  },
  {
    "id": "lms_t25",
    "name": "على سالم على سالمين الصيعري",
    "department": "مختبر التصنيع الرقمي",
    "sectionsCount": 5,
    "subjectsAndSections": "المختبرات التخصصية12 / 1 ،10 / 4 ،9 / 3 ،9 / 2 ،9 / 1 :",
    "evalCoverageRatio": "4/5",
    "evalCoveragePercent": 80.0,
    "evalUploaded": 10,
    "evalAssigned": 6,
    "evalUnassigned": 4,
    "submissionsReceived": 9,
    "submissionsGraded": 3,
    "submissionsPending": 6,
    "solveRate": 9.4,
    "gradingRate": 33.3,
    "lessonsUploaded": 10,
    "lessonsVisible": 10,
    "lessonsHidden": 0,
    "lessonsValid": 0,
    "lessonsValidPercent": 0.0,
    "missingEvalRecords": "المختبرات التخصصية12 / 1 :",
    "missingLessonRecords": "ال يوجد",
    "notes": "الدروس والتقييمات :ممتاز التقدير المعتمد :ممتاز في الدروس وممتاز في التقييمات .تقدير إداري للمهندسين والمختبرات التخصصية .المالحظات التالية تخص بيانات منصة قطر فقط .تغطية جزئية؛  1سجاًل غير ظاهر في ملف التقييمات .إسناد  4تقييًما غير مسند .استكمال تصحيح  6تسليًما .نسبة الحل أقل من ٪50؛ متابعة مشاركة الطالب في التقييمات المسندة .مراجعة استيفاء الدروس لألقسام والمالحظات ونتاجات التعلم وفق شروط المصدر.",
    "category": "followup_pending",
    "badges": [
      "التقدير المعتمد: ممتاز 🎖️",
      "6 تسليم بانتظار التصحيح ⏳",
      "تغطية تقييمات جزئية 80.0%",
      "10 درساً مسجلاً"
    ],
    "adminRating": "ممتاز",
    "adminRatingBasis": "تقدير إداري للمهندسين والمختبرات التخصصية",
    "hasActivityData": true
  },
  {
    "id": "lms_t26",
    "name": "عمران كاشف محمد حسين اسد",
    "department": "STEM",
    "sectionsCount": 1,
    "subjectsAndSections": "9 / 2 :STEM",
    "evalCoverageRatio": "1/1",
    "evalCoveragePercent": 100.0,
    "evalUploaded": 1,
    "evalAssigned": 1,
    "evalUnassigned": 0,
    "submissionsReceived": 16,
    "submissionsGraded": 16,
    "submissionsPending": 0,
    "solveRate": 100.0,
    "gradingRate": 100.0,
    "lessonsUploaded": 2,
    "lessonsVisible": 2,
    "lessonsHidden": 0,
    "lessonsValid": 0,
    "lessonsValidPercent": 0.0,
    "missingEvalRecords": "ال يوجد",
    "missingLessonRecords": "ال يوجد",
    "notes": "تغطية تقييمات كاملة تغطية رفع التقييمات كاملة في السجالت المتاحة .جميع التسليمات المسجلة مصححة .مراجعة استيفاء الدروس لألقسام والمالحظات ونتاجات التعلم وفق شروط المصدر.",
    "category": "top_overall",
    "badges": [
      "المركز 7 في المؤشر العام 🏆",
      "تصحيح 100% (16/16)",
      "تغطية تقييمات كاملة 100%",
      "2 درساً مسجلاً"
    ],
    "adminRating": "لا يوجد تعديل إداري",
    "adminRatingBasis": "",
    "hasActivityData": true,
    "generalIndex": 80.0,
    "evalIndex": 100.0,
    "lessonsIndex": 60.0
  },
  {
    "id": "lms_t27",
    "name": "فتحي المنجي بلحاج صالح",
    "department": "التربية البدنية",
    "sectionsCount": 8,
    "subjectsAndSections": "التربية البدنية11 / 4 ،11 / 3 ،11 / 2 ،11 / 1 ،10 / 4 ،10 / 3 ،10 / 2 ،10 / 1 :",
    "evalCoverageRatio": "0/8",
    "evalCoveragePercent": 0.0,
    "evalUploaded": 0,
    "evalAssigned": 0,
    "evalUnassigned": 0,
    "submissionsReceived": 0,
    "submissionsGraded": 0,
    "submissionsPending": 0,
    "solveRate": 0.0,
    "gradingRate": 0.0,
    "lessonsUploaded": 0,
    "lessonsVisible": 0,
    "lessonsHidden": 0,
    "lessonsValid": 0,
    "lessonsValidPercent": 0.0,
    "missingEvalRecords": "التربية البدنية11 / 4 ،11 / 3 ،11 / 2 ،11 / 1 ،10 / 4 ،10 / 3 ،10 / 2 ،10 / 1 :",
    "missingLessonRecords": "التربية البدنية11 / 4 ،11 / 3 ،11 / 2 ،11 / 1 ،10 / 4 ،10 / 3 ،10 / 2 ،10 / 1 :",
    "notes": "— ال يظهر سجل تقييم ال تظهر سجالت تقييم؛ يلزم التحقق من الرفع ومتطلبات المادة .استكمال الدروس في  8سجاًل .",
    "category": "followup_no_eval",
    "badges": [
      "لا توجد تقييمات مسجلة"
    ],
    "adminRating": "لا يوجد تعديل إداري",
    "adminRatingBasis": "",
    "hasActivityData": true
  },
  {
    "id": "lms_t28",
    "name": "فيصل محمد مسلم الحضري",
    "department": "الدراسات الاجتماعية",
    "sectionsCount": 6,
    "subjectsAndSections": "الدراسات االجتماعية9 / 3 ،9 / 2 ،9 / 1 ،7 / 3 ،7 / 2 ،7 / 1 :",
    "evalCoverageRatio": "6/6",
    "evalCoveragePercent": 100.0,
    "evalUploaded": 9,
    "evalAssigned": 9,
    "evalUnassigned": 0,
    "submissionsReceived": 75,
    "submissionsGraded": 75,
    "submissionsPending": 0,
    "solveRate": 52.1,
    "gradingRate": 100.0,
    "lessonsUploaded": 30,
    "lessonsVisible": 6,
    "lessonsHidden": 24,
    "lessonsValid": 0,
    "lessonsValidPercent": 0.0,
    "missingEvalRecords": "ال يوجد",
    "missingLessonRecords": "ال يوجد",
    "notes": "تغطية تقييمات كاملة تغطية رفع التقييمات كاملة في السجالت المتاحة .جميع التسليمات المسجلة مصححة .مراجعة استيفاء الدروس لألقسام والمالحظات ونتاجات التعلم وفق شروط المصدر .مراجعة جدولة إظهار  24درًسا مخفًيا؛ اإلخفاء وحده ال يثبت تقصيًر ا.",
    "category": "top_aspect",
    "badges": [
      "تصحيح 100% (75/75)",
      "تغطية تقييمات كاملة 100%",
      "30 درساً مسجلاً"
    ],
    "adminRating": "لا يوجد تعديل إداري",
    "adminRatingBasis": "",
    "hasActivityData": true
  },
  {
    "id": "lms_t29",
    "name": "كريم ولجي",
    "department": "STEM",
    "sectionsCount": 6,
    "subjectsAndSections": "علم الحاسوب11 / 3 ،10 / 4 :؛ علم الحاسوب المتقدم 12 / 5 ،12 / 3 ،12 / 2 ،12 / 1 :AP",
    "evalCoverageRatio": "3/6",
    "evalCoveragePercent": 50.0,
    "evalUploaded": 5,
    "evalAssigned": 5,
    "evalUnassigned": 0,
    "submissionsReceived": 42,
    "submissionsGraded": 35,
    "submissionsPending": 7,
    "solveRate": 56.8,
    "gradingRate": 83.3,
    "lessonsUploaded": 10,
    "lessonsVisible": 7,
    "lessonsHidden": 3,
    "lessonsValid": 0,
    "lessonsValidPercent": 0.0,
    "missingEvalRecords": "علم الحاسوب10 / 4 :؛ علم الحاسوب المتقدم 12 / 3 ،12 / 1 :AP",
    "missingLessonRecords": "ال يوجد",
    "notes": "الدروس والتقييمات :جيد جًدا التقدير المعتمد :جيد جًدا في الدروس وجيد جًدا في التقييمات .حد أدنى إداري لمعلمي الصف الثاني عشر الستخدام منصات تعليمية أخرى ،وفق إفادة اإلدارة .المالحظات التالية تخص بيانات منصة قطر فقط .تغطية جزئية؛  3سجاًل غير ظاهر في ملف التقييمات .استكمال تصحيح  7تسليًما .مراجعة استيفاء الدروس لألقسام والمالحظات ونتاجات التعلم وفق شروط المصدر .مراجعة جدولة إظهار  3درًسا مخفًيا؛ اإلخفاء وحده ال يثبت تقصيًر ا.",
    "category": "followup_pending",
    "badges": [
      "التقدير المعتمد: جيد جداً 🎖️",
      "7 تسليم بانتظار التصحيح ⏳",
      "تغطية تقييمات جزئية 50.0%",
      "10 درساً مسجلاً"
    ],
    "adminRating": "جيد جداً",
    "adminRatingBasis": "حد أدنى إداري لمعلمي الصف الثاني عشر لاستخدام منصات تعليمية أخرى، وفق إفادة الإدارة",
    "hasActivityData": true
  },
  {
    "id": "lms_t30",
    "name": "كليفرد جورج بايلي",
    "department": "الرياضيات",
    "sectionsCount": 2,
    "subjectsAndSections": "التفاضل والتكامل التمهيدي 11 / 4 :AP؛ الرياضيات10 / 4 :",
    "evalCoverageRatio": "0/2",
    "evalCoveragePercent": 0.0,
    "evalUploaded": 0,
    "evalAssigned": 0,
    "evalUnassigned": 0,
    "submissionsReceived": 0,
    "submissionsGraded": 0,
    "submissionsPending": 0,
    "solveRate": 0.0,
    "gradingRate": 0.0,
    "lessonsUploaded": 18,
    "lessonsVisible": 18,
    "lessonsHidden": 0,
    "lessonsValid": 0,
    "lessonsValidPercent": 0.0,
    "missingEvalRecords": "التفاضل والتكامل التمهيدي 11 / 4 :AP؛ الرياضيات10 / 4 :",
    "missingLessonRecords": "ال يوجد",
    "notes": "— ال يظهر سجل تقييم ال تظهر سجالت تقييم؛ يلزم التحقق من الرفع ومتطلبات المادة .مراجعة استيفاء الدروس لألقسام والمالحظات ونتاجات التعلم وفق شروط المصدر.",
    "category": "followup_no_eval",
    "badges": [
      "لا توجد تقييمات مسجلة",
      "18 درساً مسجلاً"
    ],
    "adminRating": "لا يوجد تعديل إداري",
    "adminRatingBasis": "",
    "hasActivityData": true
  },
  {
    "id": "lms_t31",
    "name": "محمد سامي ابراهيم عبدالقادر الكفرى",
    "department": "الحاسوب",
    "sectionsCount": 5,
    "subjectsAndSections": "علم الحاسوب11 / 2 ،11 / 1 ،7 / 3 ،7 / 2 ،7 / 1 :",
    "evalCoverageRatio": "3/5",
    "evalCoveragePercent": 60.0,
    "evalUploaded": 3,
    "evalAssigned": 3,
    "evalUnassigned": 0,
    "submissionsReceived": 35,
    "submissionsGraded": 0,
    "submissionsPending": 35,
    "solveRate": 72.9,
    "gradingRate": 0.0,
    "lessonsUploaded": 5,
    "lessonsVisible": 5,
    "lessonsHidden": 0,
    "lessonsValid": 0,
    "lessonsValidPercent": 0.0,
    "missingEvalRecords": "علم الحاسوب11 / 2 ،11 / 1 :",
    "missingLessonRecords": "ال يوجد",
    "notes": "تغطية تقييمات جزئية تغطية جزئية؛  2سجاًل غير ظاهر في ملف التقييمات .استكمال تصحيح  35تسليًما .مراجعة استيفاء الدروس لألقسام والمالحظات ونتاجات التعلم وفق شروط المصدر.",
    "category": "followup_pending",
    "badges": [
      "35 تسليم بانتظار التصحيح ⏳",
      "تغطية تقييمات جزئية 60.0%",
      "5 درساً مسجلاً"
    ],
    "adminRating": "لا يوجد تعديل إداري",
    "adminRatingBasis": "",
    "hasActivityData": true
  },
  {
    "id": "lms_t32",
    "name": "محمد سيد ميردادي",
    "department": "اللغة الإنجليزية",
    "sectionsCount": 7,
    "subjectsAndSections": "اللغة االنجليزية11 / 4 ،11 / 3 ،11 / 2 ،11 / 1 ،9 / 3 ،9 / 2 ،9 / 1 :",
    "evalCoverageRatio": "4/7",
    "evalCoveragePercent": 57.1,
    "evalUploaded": 4,
    "evalAssigned": 4,
    "evalUnassigned": 0,
    "submissionsReceived": 42,
    "submissionsGraded": 0,
    "submissionsPending": 42,
    "solveRate": 70.0,
    "gradingRate": 0.0,
    "lessonsUploaded": 95,
    "lessonsVisible": 4,
    "lessonsHidden": 91,
    "lessonsValid": 91,
    "lessonsValidPercent": 95.8,
    "missingEvalRecords": "اللغة االنجليزية9 / 3 ،9 / 2 ،9 / 1 :",
    "missingLessonRecords": "ال يوجد",
    "notes": "تغطية تقييمات جزئية تغطية جزئية؛  3سجاًل غير ظاهر في ملف التقييمات .استكمال تصحيح  42تسليًما .مراجعة استيفاء الدروس لألقسام والمالحظات ونتاجات التعلم وفق شروط المصدر .مراجعة جدولة إظهار  91درًسا مخفًيا؛ اإلخفاء وحده ال يثبت تقصيًر ا.",
    "category": "followup_pending",
    "badges": [
      "42 تسليم بانتظار التصحيح ⏳",
      "تغطية تقييمات جزئية 57.1%",
      "95 درساً مسجلاً"
    ],
    "adminRating": "لا يوجد تعديل إداري",
    "adminRatingBasis": "",
    "hasActivityData": true
  },
  {
    "id": "lms_t33",
    "name": "محمد شفاتا احمد",
    "department": "التصميم التكنولوجي",
    "sectionsCount": 3,
    "subjectsAndSections": "تكنولوجيا التصميم7 / 3 ،7 / 2 ،7 / 1 :",
    "evalCoverageRatio": "3/3",
    "evalCoveragePercent": 100.0,
    "evalUploaded": 3,
    "evalAssigned": 1,
    "evalUnassigned": 2,
    "submissionsReceived": 0,
    "submissionsGraded": 0,
    "submissionsPending": 0,
    "solveRate": 0.0,
    "gradingRate": 0.0,
    "lessonsUploaded": 12,
    "lessonsVisible": 12,
    "lessonsHidden": 0,
    "lessonsValid": 0,
    "lessonsValidPercent": 0.0,
    "missingEvalRecords": "ال يوجد",
    "missingLessonRecords": "ال يوجد",
    "notes": "— الدروس والتقييمات :جيد جًدا التقدير المعتمد :جيد جًدا في الدروس وجيد جًدا في التقييمات .تقدير إداري لمعلمي مادة التصميم التكنولوجي وفق اعتماد اإلدارة .المالحظات التالية تخص بيانات منصة قطر فقط .تغطية رفع التقييمات كاملة في السجالت المتاحة .إسناد 2تقييًما غير مسند .نسبة الحل أقل من ٪50؛ متابعة مشاركة الطالب في التقييمات المسندة .مراجعة استيفاء الدروس لألقسام والمالحظات ونتاجات التعلم وفق شروط المصدر.",
    "category": "top_aspect",
    "badges": [
      "التقدير المعتمد: جيد جداً 🎖️",
      "تغطية تقييمات كاملة 100%",
      "12 درساً مسجلاً"
    ],
    "adminRating": "جيد جداً",
    "adminRatingBasis": "تقدير إداري لمعلمي مادة التصميم التكنولوجي وفق اعتماد الإدارة",
    "hasActivityData": true
  },
  {
    "id": "lms_t34",
    "name": "محمد عادل عبدالعزيز الطاهر",
    "department": "اللغة العربية",
    "sectionsCount": 4,
    "subjectsAndSections": "اللغة العربية11 / 4 ،11 / 3 ،11 / 2 ،11 / 1 :",
    "evalCoverageRatio": "3/4",
    "evalCoveragePercent": 75.0,
    "evalUploaded": 7,
    "evalAssigned": 7,
    "evalUnassigned": 0,
    "submissionsReceived": 73,
    "submissionsGraded": 73,
    "submissionsPending": 0,
    "solveRate": 70.2,
    "gradingRate": 100.0,
    "lessonsUploaded": 77,
    "lessonsVisible": 33,
    "lessonsHidden": 44,
    "lessonsValid": 77,
    "lessonsValidPercent": 100.0,
    "missingEvalRecords": "اللغة العربية11 / 3 :",
    "missingLessonRecords": "ال يوجد",
    "notes": "تغطية تقييمات جزئية تغطية جزئية؛  1سجاًل غير ظاهر في ملف التقييمات .جميع التسليمات المسجلة مصححة .جميع الدروس محسوبة وفق شروط المصدر .مراجعة جدولة إظهار  44درًسا مخفًيا؛ اإلخفاء وحده ال يثبت تقصيًر ا.",
    "category": "top_overall",
    "badges": [
      "المركز 4 في المؤشر العام 🏆",
      "تصحيح 100% (73/73)",
      "تغطية تقييمات جزئية 75.0%",
      "77 درساً مسجلاً"
    ],
    "adminRating": "لا يوجد تعديل إداري",
    "adminRatingBasis": "",
    "hasActivityData": true,
    "generalIndex": 89.29,
    "evalIndex": 90.0,
    "lessonsIndex": 88.57
  },
  {
    "id": "lms_t35",
    "name": "محمد عالءالدين محمد عوض هللا",
    "department": "التربية البدنية",
    "sectionsCount": 6,
    "subjectsAndSections": "التربية البدنية9 / 3 ،9 / 2 ،9 / 1 ،7 / 3 ،7 / 2 ،7 / 1 :",
    "evalCoverageRatio": "0/6",
    "evalCoveragePercent": 0.0,
    "evalUploaded": 0,
    "evalAssigned": 0,
    "evalUnassigned": 0,
    "submissionsReceived": 0,
    "submissionsGraded": 0,
    "submissionsPending": 0,
    "solveRate": 0.0,
    "gradingRate": 0.0,
    "lessonsUploaded": 0,
    "lessonsVisible": 0,
    "lessonsHidden": 0,
    "lessonsValid": 0,
    "lessonsValidPercent": 0.0,
    "missingEvalRecords": "التربية البدنية9 / 3 ،9 / 2 ،9 / 1 ،7 / 3 ،7 / 2 ،7 / 1 :",
    "missingLessonRecords": "التربية البدنية9 / 3 ،9 / 2 ،9 / 1 ،7 / 3 ،7 / 2 ،7 / 1 :",
    "notes": "— ال يظهر سجل تقييم ال تظهر سجالت تقييم؛ يلزم التحقق من الرفع ومتطلبات المادة .استكمال الدروس في  6سجاًل .",
    "category": "followup_no_eval",
    "badges": [
      "لا توجد تقييمات مسجلة"
    ],
    "adminRating": "لا يوجد تعديل إداري",
    "adminRatingBasis": "",
    "hasActivityData": true
  },
  {
    "id": "lms_t36",
    "name": "محمد عماد ازكول",
    "department": "الرياضيات",
    "sectionsCount": 3,
    "subjectsAndSections": "الرياضيات7 / 3 ،7 / 2 ،7 / 1 :",
    "evalCoverageRatio": "0/3",
    "evalCoveragePercent": 0.0,
    "evalUploaded": 0,
    "evalAssigned": 0,
    "evalUnassigned": 0,
    "submissionsReceived": 0,
    "submissionsGraded": 0,
    "submissionsPending": 0,
    "solveRate": 0.0,
    "gradingRate": 0.0,
    "lessonsUploaded": 12,
    "lessonsVisible": 12,
    "lessonsHidden": 0,
    "lessonsValid": 0,
    "lessonsValidPercent": 0.0,
    "missingEvalRecords": "الرياضيات7 / 3 ،7 / 2 ،7 / 1 :",
    "missingLessonRecords": "ال يوجد",
    "notes": "— ال يظهر سجل تقييم ال تظهر سجالت تقييم؛ يلزم التحقق من الرفع ومتطلبات المادة .مراجعة استيفاء الدروس لألقسام والمالحظات ونتاجات التعلم وفق شروط المصدر.",
    "category": "followup_no_eval",
    "badges": [
      "لا توجد تقييمات مسجلة",
      "12 درساً مسجلاً"
    ],
    "adminRating": "لا يوجد تعديل إداري",
    "adminRatingBasis": "",
    "hasActivityData": true
  },
  {
    "id": "lms_t37",
    "name": "محمد عيسي دادي",
    "department": "اللغة الإنجليزية",
    "sectionsCount": 2,
    "subjectsAndSections": "9 / 3 ،7 / 3 :STEM",
    "evalCoverageRatio": "0/2",
    "evalCoveragePercent": 0.0,
    "evalUploaded": 0,
    "evalAssigned": 0,
    "evalUnassigned": 0,
    "submissionsReceived": 0,
    "submissionsGraded": 0,
    "submissionsPending": 0,
    "solveRate": 0.0,
    "gradingRate": 0.0,
    "lessonsUploaded": 3,
    "lessonsVisible": 3,
    "lessonsHidden": 0,
    "lessonsValid": 0,
    "lessonsValidPercent": 0.0,
    "missingEvalRecords": "9 / 3 ،7 / 3 :STEM",
    "missingLessonRecords": "ال يوجد",
    "notes": "— ال يظهر سجل تقييم ال تظهر سجالت تقييم؛ يلزم التحقق من الرفع ومتطلبات المادة .مراجعة استيفاء الدروس لألقسام والمالحظات ونتاجات التعلم وفق شروط المصدر.",
    "category": "followup_no_eval",
    "badges": [
      "لا توجد تقييمات مسجلة",
      "3 درساً مسجلاً"
    ],
    "adminRating": "لا يوجد تعديل إداري",
    "adminRatingBasis": "",
    "hasActivityData": true
  },
  {
    "id": "lms_t38",
    "name": "محمد قاسم",
    "department": "الرياضيات",
    "sectionsCount": 3,
    "subjectsAndSections": "الرياضيات10 / 2 ،10 / 1 ،9 / 1 :",
    "evalCoverageRatio": "0/3",
    "evalCoveragePercent": 0.0,
    "evalUploaded": 0,
    "evalAssigned": 0,
    "evalUnassigned": 0,
    "submissionsReceived": 0,
    "submissionsGraded": 0,
    "submissionsPending": 0,
    "solveRate": 0.0,
    "gradingRate": 0.0,
    "lessonsUploaded": 11,
    "lessonsVisible": 11,
    "lessonsHidden": 0,
    "lessonsValid": 0,
    "lessonsValidPercent": 0.0,
    "missingEvalRecords": "الرياضيات10 / 2 ،10 / 1 ،9 / 1 :",
    "missingLessonRecords": "ال يوجد",
    "notes": "— ال يظهر سجل تقييم ال تظهر سجالت تقييم؛ يلزم التحقق من الرفع ومتطلبات المادة .مراجعة استيفاء الدروس لألقسام والمالحظات ونتاجات التعلم وفق شروط المصدر.",
    "category": "followup_no_eval",
    "badges": [
      "لا توجد تقييمات مسجلة",
      "11 درساً مسجلاً"
    ],
    "adminRating": "لا يوجد تعديل إداري",
    "adminRatingBasis": "",
    "hasActivityData": true
  },
  {
    "id": "lms_t39",
    "name": "محمد كمال محمد زيد",
    "department": "الرياضيات",
    "sectionsCount": 4,
    "subjectsAndSections": "التفاضل والتكامل 12 / 5 ،12 / 3 :AP؛ التفاضل والتكامل التمهيدي 11 / 2 ،11 / 1 :AP",
    "evalCoverageRatio": "0/4",
    "evalCoveragePercent": 0.0,
    "evalUploaded": 0,
    "evalAssigned": 0,
    "evalUnassigned": 0,
    "submissionsReceived": 0,
    "submissionsGraded": 0,
    "submissionsPending": 0,
    "solveRate": 0.0,
    "gradingRate": 0.0,
    "lessonsUploaded": 7,
    "lessonsVisible": 7,
    "lessonsHidden": 0,
    "lessonsValid": 0,
    "lessonsValidPercent": 0.0,
    "missingEvalRecords": "التفاضل والتكامل 12 / 5 ،12 / 3 :AP؛ التفاضل والتكامل التمهيدي 11 / 2 ،11 / 1 :AP",
    "missingLessonRecords": "ال يوجد",
    "notes": "— الدروس والتقييمات :جيد جًدا التقدير المعتمد :جيد جًدا في الدروس وجيد جًدا في التقييمات .حد أدنى إداري لمعلمي الصف الثاني عشر الستخدام منصات تعليمية أخرى ،وفق إفادة اإلدارة .المالحظات التالية تخص بيانات منصة قطر فقط .ال تظهر سجالت تقييم؛ يلزم التحقق من الرفع ومتطلبات المادة .مراجعة استيفاء الدروس لألقسام والمالحظات ونتاجات التعلم وفق شروط المصدر.",
    "category": "followup_no_eval",
    "badges": [
      "التقدير المعتمد: جيد جداً 🎖️",
      "لا توجد تقييمات مسجلة",
      "7 درساً مسجلاً"
    ],
    "adminRating": "جيد جداً",
    "adminRatingBasis": "حد أدنى إداري لمعلمي الصف الثاني عشر لاستخدام منصات تعليمية أخرى، وفق إفادة الإدارة",
    "hasActivityData": true
  },
  {
    "id": "lms_t40",
    "name": "محمد ورسامي عمر",
    "department": "اللغة الإنجليزية",
    "sectionsCount": 7,
    "subjectsAndSections": "اللغة االنجليزية10 / 4 ،10 / 3 ،10 / 2 ،10 / 1 ،7 / 3 ،7 / 2 ،7 / 1 :",
    "evalCoverageRatio": "0/7",
    "evalCoveragePercent": 0.0,
    "evalUploaded": 0,
    "evalAssigned": 0,
    "evalUnassigned": 0,
    "submissionsReceived": 0,
    "submissionsGraded": 0,
    "submissionsPending": 0,
    "solveRate": 0.0,
    "gradingRate": 0.0,
    "lessonsUploaded": 103,
    "lessonsVisible": 18,
    "lessonsHidden": 85,
    "lessonsValid": 81,
    "lessonsValidPercent": 78.6,
    "missingEvalRecords": "اللغة االنجليزية10 / 4 ،10 / 3 ،10 / 2 ،10 / 1 ،7 / 3 ،7 / 2 ،7 / 1 :",
    "missingLessonRecords": "ال يوجد",
    "notes": "— ال يظهر سجل تقييم ال تظهر سجالت تقييم؛ يلزم التحقق من الرفع ومتطلبات المادة .مراجعة استيفاء الدروس لألقسام والمالحظات ونتاجات التعلم وفق شروط المصدر .مراجعة جدولة إظهار  85درًسا مخفًيا؛ اإلخفاء وحده ال يثبت تقصيًر ا.",
    "category": "followup_no_eval",
    "badges": [
      "لا توجد تقييمات مسجلة",
      "103 درساً مسجلاً"
    ],
    "adminRating": "لا يوجد تعديل إداري",
    "adminRatingBasis": "",
    "hasActivityData": true
  },
  {
    "id": "lms_t41",
    "name": "ناصر احمد حسن حلوة",
    "department": "التربية الإسلامية",
    "sectionsCount": 6,
    "subjectsAndSections": "التربية االسالمية12 / 4 ،12 / 3 ،12 / 2 ،12 / 1 ،10 / 2 ،10 / 1 :",
    "evalCoverageRatio": "6/6",
    "evalCoveragePercent": 100.0,
    "evalUploaded": 19,
    "evalAssigned": 9,
    "evalUnassigned": 10,
    "submissionsReceived": 101,
    "submissionsGraded": 101,
    "submissionsPending": 0,
    "solveRate": 70.1,
    "gradingRate": 100.0,
    "lessonsUploaded": 49,
    "lessonsVisible": 49,
    "lessonsHidden": 0,
    "lessonsValid": 33,
    "lessonsValidPercent": 67.3,
    "missingEvalRecords": "ال يوجد",
    "missingLessonRecords": "ال يوجد",
    "notes": "الدروس والتقييمات :جيد جًدا التقدير المعتمد :جيد جًدا في الدروس وجيد جًدا في التقييمات .حد أدنى إداري لمعلمي الصف الثاني عشر الستخدام منصات تعليمية أخرى ،وفق إفادة اإلدارة .المالحظات التالية تخص بيانات منصة قطر فقط .تغطية رفع التقييمات كاملة في السجالت المتاحة .إسناد  10تقييًما غير مسند .جميع التسليمات المسجلة مصححة .مراجعة استيفاء الدروس لألقسام والمالحظات ونتاجات التعلم وفق شروط المصدر.",
    "category": "top_overall",
    "badges": [
      "المركز 5 في المؤشر العام 🏆",
      "التقدير المعتمد: جيد جداً 🎖️",
      "تصحيح 100% (101/101)",
      "تغطية تقييمات كاملة 100%",
      "49 درساً مسجلاً"
    ],
    "adminRating": "جيد جداً",
    "adminRatingBasis": "حد أدنى إداري لمعلمي الصف الثاني عشر لاستخدام منصات تعليمية أخرى، وفق إفادة الإدارة",
    "hasActivityData": true,
    "generalIndex": 85.57,
    "evalIndex": 84.21,
    "lessonsIndex": 86.94
  },
  {
    "id": "lms_t42",
    "name": "نزار بن عبدهللا حاجي",
    "department": "STEM",
    "sectionsCount": 3,
    "subjectsAndSections": "فيزياء الميكانيكا 12 / 5 ،12 / 4 ،12 / 3 :C-AP",
    "evalCoverageRatio": "0/3",
    "evalCoveragePercent": 0.0,
    "evalUploaded": 0,
    "evalAssigned": 0,
    "evalUnassigned": 0,
    "submissionsReceived": 0,
    "submissionsGraded": 0,
    "submissionsPending": 0,
    "solveRate": 0.0,
    "gradingRate": 0.0,
    "lessonsUploaded": 2,
    "lessonsVisible": 2,
    "lessonsHidden": 0,
    "lessonsValid": 0,
    "lessonsValidPercent": 0.0,
    "missingEvalRecords": "فيزياء الميكانيكا 12 / 5 ،12 / 4 ،12 / 3 :C-AP",
    "missingLessonRecords": "فيزياء الميكانيكا 12 / 5 :C-AP",
    "notes": "— الدروس والتقييمات :جيد جًدا التقدير المعتمد :جيد جًدا في الدروس وجيد جًدا في التقييمات .حد أدنى إداري لمعلمي الصف الثاني عشر الستخدام منصات تعليمية أخرى ،وفق إفادة اإلدارة .المالحظات التالية تخص بيانات منصة قطر فقط .ال تظهر سجالت تقييم؛ يلزم التحقق من الرفع ومتطلبات المادة .استكمال الدروس في  1سجاًل  .مراجعة استيفاء الدروس لألقسام والمالحظات ونتاجات التعلم وفق شروط المصدر.",
    "category": "followup_no_eval",
    "badges": [
      "التقدير المعتمد: جيد جداً 🎖️",
      "لا توجد تقييمات مسجلة",
      "2 درساً مسجلاً"
    ],
    "adminRating": "جيد جداً",
    "adminRatingBasis": "حد أدنى إداري لمعلمي الصف الثاني عشر لاستخدام منصات تعليمية أخرى، وفق إفادة الإدارة",
    "hasActivityData": true
  },
  {
    "id": "lms_t43",
    "name": "هشام محمد امام سليمان",
    "department": "اللغة العربية",
    "sectionsCount": 5,
    "subjectsAndSections": "اللغة العربية12 / 5 ،12 / 4 ،12 / 3 ،12 / 2 ،12 / 1 :",
    "evalCoverageRatio": "0/5",
    "evalCoveragePercent": 0.0,
    "evalUploaded": 0,
    "evalAssigned": 0,
    "evalUnassigned": 0,
    "submissionsReceived": 0,
    "submissionsGraded": 0,
    "submissionsPending": 0,
    "solveRate": 0.0,
    "gradingRate": 0.0,
    "lessonsUploaded": 49,
    "lessonsVisible": 49,
    "lessonsHidden": 0,
    "lessonsValid": 49,
    "lessonsValidPercent": 100.0,
    "missingEvalRecords": "اللغة العربية12 / 5 ،12 / 4 ،12 / 3 ،12 / 2 ،12 / 1 :",
    "missingLessonRecords": "ال يوجد  نواقص التقييمات ضمن السجالت المتاحة  29معلًما من أصل  43ال تظهر تقييمات في جميع سجالتهم 9 :بتغطية جزئية و 20بال سجالت تقييم .التسعة غير الظاهرين في كال الملفين مدرجون منفصلين مع تقديراتهم المعتمدة .نواقص المنصة ال تلغي التقديرات اإلدارية أو مراعاة استخدام منصات أخرى.  تغطية جزئية المعلم  المغطى  /اإلجمالي  السجالت غير الظاهرة  احمد اسامه صقر المعاني  8 / 21  البحث واالبتكار9 / 3 ،9 / 2 ،9 / 1 ،7 / 3 ،7 / 2 ،7 / 1 :؛ تكنولوجيا التصميم10 / 4 ،10 / 3 ،10 / 2 ،10 / 1 ،9 / 3 ،9 / 2 ،9 / 1 :  راجي ترابي  1/3  9 / 1 ،7 / 1 :STEM  عبدالعزيز محمد  4/7  المختبرات التخصصية12 / 4 ،11 / 4 ،11 / 2 :  عالء حسني محمد موسى  2/3  التربية االسالمية12 / 5 :",
    "notes": "— الدروس والتقييمات :جيد جًدا التقدير المعتمد :جيد جًدا في الدروس وجيد جًدا في التقييمات .حد أدنى إداري لمعلمي الصف الثاني عشر الستخدام منصات تعليمية أخرى ،وفق إفادة اإلدارة .المالحظات التالية تخص بيانات منصة قطر فقط .ال تظهر سجالت تقييم؛ يلزم التحقق من الرفع ومتطلبات المادة .جميع الدروس محسوبة وفق شروط المصدر.",
    "category": "followup_no_eval",
    "badges": [
      "التقدير المعتمد: جيد جداً 🎖️",
      "لا توجد تقييمات مسجلة",
      "49 درساً مسجلاً"
    ],
    "adminRating": "جيد جداً",
    "adminRatingBasis": "حد أدنى إداري لمعلمي الصف الثاني عشر لاستخدام منصات تعليمية أخرى، وفق إفادة الإدارة",
    "hasActivityData": true
  },
  {
    "id": "lms_t44",
    "name": "ابراهيم عونى عمر حسن النعيمى",
    "department": "مختبر الطاقة",
    "sectionsCount": 0,
    "subjectsAndSections": "مختبر الطاقة التخصصي",
    "evalCoverageRatio": "0/0",
    "evalCoveragePercent": 0,
    "evalUploaded": 0,
    "evalAssigned": 0,
    "evalUnassigned": 0,
    "submissionsReceived": 0,
    "submissionsGraded": 0,
    "submissionsPending": 0,
    "solveRate": 0,
    "gradingRate": 0,
    "lessonsUploaded": 0,
    "lessonsVisible": 0,
    "lessonsHidden": 0,
    "lessonsValid": 0,
    "lessonsValidPercent": 0,
    "missingEvalRecords": "لا تظهر سجلات في ملفي النشاط",
    "missingLessonRecords": "لا تظهر سجلات في ملفي النشاط",
    "notes": "التقدير المعتمد: ممتاز في الدروس وممتاز في التقييمات. تقدير إداري للمهندسين والمختبرات التخصصية.",
    "category": "top_aspect",
    "badges": [
      "التقدير المعتمد: ممتاز 🎖️",
      "مهندس مختبر تخصصي"
    ],
    "adminRating": "ممتاز",
    "adminRatingBasis": "تقدير إداري للمهندسين والمختبرات التخصصية",
    "hasActivityData": false
  },
  {
    "id": "lms_t45",
    "name": "اياد محمود علي سالمه",
    "department": "مختبر الروبوت",
    "sectionsCount": 0,
    "subjectsAndSections": "مختبر الروبوت التخصصي",
    "evalCoverageRatio": "0/0",
    "evalCoveragePercent": 0,
    "evalUploaded": 0,
    "evalAssigned": 0,
    "evalUnassigned": 0,
    "submissionsReceived": 0,
    "submissionsGraded": 0,
    "submissionsPending": 0,
    "solveRate": 0,
    "gradingRate": 0,
    "lessonsUploaded": 0,
    "lessonsVisible": 0,
    "lessonsHidden": 0,
    "lessonsValid": 0,
    "lessonsValidPercent": 0,
    "missingEvalRecords": "لا تظهر سجلات في ملفي النشاط",
    "missingLessonRecords": "لا تظهر سجلات في ملفي النشاط",
    "notes": "التقدير المعتمد: ممتاز في الدروس وممتاز في التقييمات. تقدير إداري للمهندسين والمختبرات التخصصية.",
    "category": "top_aspect",
    "badges": [
      "التقدير المعتمد: ممتاز 🎖️",
      "مهندس مختبر تخصصي"
    ],
    "adminRating": "ممتاز",
    "adminRatingBasis": "تقدير إداري للمهندسين والمختبرات التخصصية",
    "hasActivityData": false
  },
  {
    "id": "lms_t46",
    "name": "محمود علم اقبال احمد",
    "department": "مختبر الروبوت",
    "sectionsCount": 0,
    "subjectsAndSections": "مختبر الروبوت التخصصي",
    "evalCoverageRatio": "0/0",
    "evalCoveragePercent": 0,
    "evalUploaded": 0,
    "evalAssigned": 0,
    "evalUnassigned": 0,
    "submissionsReceived": 0,
    "submissionsGraded": 0,
    "submissionsPending": 0,
    "solveRate": 0,
    "gradingRate": 0,
    "lessonsUploaded": 0,
    "lessonsVisible": 0,
    "lessonsHidden": 0,
    "lessonsValid": 0,
    "lessonsValidPercent": 0,
    "missingEvalRecords": "لا تظهر سجلات في ملفي النشاط",
    "missingLessonRecords": "لا تظهر سجلات في ملفي النشاط",
    "notes": "التقدير المعتمد: ممتاز في الدروس وممتاز في التقييمات. تقدير إداري للمهندسين والمختبرات التخصصية.",
    "category": "top_aspect",
    "badges": [
      "التقدير المعتمد: ممتاز 🎖️",
      "مهندس مختبر تخصصي"
    ],
    "adminRating": "ممتاز",
    "adminRatingBasis": "تقدير إداري للمهندسين والمختبرات التخصصية",
    "hasActivityData": false
  },
  {
    "id": "lms_t47",
    "name": "اوزدن اوزغور",
    "department": "STEM",
    "sectionsCount": 0,
    "subjectsAndSections": "STEM",
    "evalCoverageRatio": "0/0",
    "evalCoveragePercent": 0,
    "evalUploaded": 0,
    "evalAssigned": 0,
    "evalUnassigned": 0,
    "submissionsReceived": 0,
    "submissionsGraded": 0,
    "submissionsPending": 0,
    "solveRate": 0,
    "gradingRate": 0,
    "lessonsUploaded": 0,
    "lessonsVisible": 0,
    "lessonsHidden": 0,
    "lessonsValid": 0,
    "lessonsValidPercent": 0,
    "missingEvalRecords": "لا تظهر سجلات في ملفي النشاط",
    "missingLessonRecords": "لا تظهر سجلات في ملفي النشاط",
    "notes": "التقدير المعتمد: جيد جداً في الدروس وجيد جداً في التقييمات. تقدير إداري للمعلمين ضمن النطاق دون بيانات نشاط متاحة.",
    "category": "top_aspect",
    "badges": [
      "التقدير المعتمد: جيد جداً 🎖️",
      "ضمن نطاق التقرير الإداري"
    ],
    "adminRating": "جيد جداً",
    "adminRatingBasis": "تقدير إداري للمعلمين ضمن النطاق دون بيانات نشاط متاحة",
    "hasActivityData": false
  },
  {
    "id": "lms_t48",
    "name": "ايلفيس ايلوم تيتي",
    "department": "اللغة الإنجليزية",
    "sectionsCount": 0,
    "subjectsAndSections": "اللغة الإنجليزية",
    "evalCoverageRatio": "0/0",
    "evalCoveragePercent": 0,
    "evalUploaded": 0,
    "evalAssigned": 0,
    "evalUnassigned": 0,
    "submissionsReceived": 0,
    "submissionsGraded": 0,
    "submissionsPending": 0,
    "solveRate": 0,
    "gradingRate": 0,
    "lessonsUploaded": 0,
    "lessonsVisible": 0,
    "lessonsHidden": 0,
    "lessonsValid": 0,
    "lessonsValidPercent": 0,
    "missingEvalRecords": "لا تظهر سجلات في ملفي النشاط",
    "missingLessonRecords": "لا تظهر سجلات في ملفي النشاط",
    "notes": "التقدير المعتمد: جيد جداً في الدروس وجيد جداً في التقييمات. تقدير إداري للمعلمين ضمن النطاق دون بيانات نشاط متاحة.",
    "category": "top_aspect",
    "badges": [
      "التقدير المعتمد: جيد جداً 🎖️",
      "ضمن نطاق التقرير الإداري"
    ],
    "adminRating": "جيد جداً",
    "adminRatingBasis": "تقدير إداري للمعلمين ضمن النطاق دون بيانات نشاط متاحة",
    "hasActivityData": false
  },
  {
    "id": "lms_t49",
    "name": "زايد كاظم",
    "department": "STEM",
    "sectionsCount": 0,
    "subjectsAndSections": "STEM",
    "evalCoverageRatio": "0/0",
    "evalCoveragePercent": 0,
    "evalUploaded": 0,
    "evalAssigned": 0,
    "evalUnassigned": 0,
    "submissionsReceived": 0,
    "submissionsGraded": 0,
    "submissionsPending": 0,
    "solveRate": 0,
    "gradingRate": 0,
    "lessonsUploaded": 0,
    "lessonsVisible": 0,
    "lessonsHidden": 0,
    "lessonsValid": 0,
    "lessonsValidPercent": 0,
    "missingEvalRecords": "لا تظهر سجلات في ملفي النشاط",
    "missingLessonRecords": "لا تظهر سجلات في ملفي النشاط",
    "notes": "التقدير المعتمد: جيد جداً في الدروس وجيد جداً في التقييمات. تقدير إداري للمعلمين ضمن النطاق دون بيانات نشاط متاحة.",
    "category": "top_aspect",
    "badges": [
      "التقدير المعتمد: جيد جداً 🎖️",
      "ضمن نطاق التقرير الإداري"
    ],
    "adminRating": "جيد جداً",
    "adminRatingBasis": "تقدير إداري للمعلمين ضمن النطاق دون بيانات نشاط متاحة",
    "hasActivityData": false
  },
  {
    "id": "lms_t50",
    "name": "سليمان ميا",
    "department": "STEM",
    "sectionsCount": 0,
    "subjectsAndSections": "STEM",
    "evalCoverageRatio": "0/0",
    "evalCoveragePercent": 0,
    "evalUploaded": 0,
    "evalAssigned": 0,
    "evalUnassigned": 0,
    "submissionsReceived": 0,
    "submissionsGraded": 0,
    "submissionsPending": 0,
    "solveRate": 0,
    "gradingRate": 0,
    "lessonsUploaded": 0,
    "lessonsVisible": 0,
    "lessonsHidden": 0,
    "lessonsValid": 0,
    "lessonsValidPercent": 0,
    "missingEvalRecords": "لا تظهر سجلات في ملفي النشاط",
    "missingLessonRecords": "لا تظهر سجلات في ملفي النشاط",
    "notes": "التقدير المعتمد: جيد جداً في الدروس وجيد جداً في التقييمات. تقدير إداري للمعلمين ضمن النطاق دون بيانات نشاط متاحة.",
    "category": "top_aspect",
    "badges": [
      "التقدير المعتمد: جيد جداً 🎖️",
      "ضمن نطاق التقرير الإداري"
    ],
    "adminRating": "جيد جداً",
    "adminRatingBasis": "تقدير إداري للمعلمين ضمن النطاق دون بيانات نشاط متاحة",
    "hasActivityData": false
  },
  {
    "id": "lms_t51",
    "name": "فوزي عصام بو فخرالدين",
    "department": "STEM",
    "sectionsCount": 0,
    "subjectsAndSections": "STEM",
    "evalCoverageRatio": "0/0",
    "evalCoveragePercent": 0,
    "evalUploaded": 0,
    "evalAssigned": 0,
    "evalUnassigned": 0,
    "submissionsReceived": 0,
    "submissionsGraded": 0,
    "submissionsPending": 0,
    "solveRate": 0,
    "gradingRate": 0,
    "lessonsUploaded": 0,
    "lessonsVisible": 0,
    "lessonsHidden": 0,
    "lessonsValid": 0,
    "lessonsValidPercent": 0,
    "missingEvalRecords": "لا تظهر سجلات في ملفي النشاط",
    "missingLessonRecords": "لا تظهر سجلات في ملفي النشاط",
    "notes": "التقدير المعتمد: جيد جداً في الدروس وجيد جداً في التقييمات. تقدير إداري للمعلمين ضمن النطاق دون بيانات نشاط متاحة.",
    "category": "top_aspect",
    "badges": [
      "التقدير المعتمد: جيد جداً 🎖️",
      "ضمن نطاق التقرير الإداري"
    ],
    "adminRating": "جيد جداً",
    "adminRatingBasis": "تقدير إداري للمعلمين ضمن النطاق دون بيانات نشاط متاحة",
    "hasActivityData": false
  },
  {
    "id": "lms_t52",
    "name": "نبيل صالح الدين عطيه ايوب",
    "department": "STEM",
    "sectionsCount": 0,
    "subjectsAndSections": "STEM",
    "evalCoverageRatio": "0/0",
    "evalCoveragePercent": 0,
    "evalUploaded": 0,
    "evalAssigned": 0,
    "evalUnassigned": 0,
    "submissionsReceived": 0,
    "submissionsGraded": 0,
    "submissionsPending": 0,
    "solveRate": 0,
    "gradingRate": 0,
    "lessonsUploaded": 0,
    "lessonsVisible": 0,
    "lessonsHidden": 0,
    "lessonsValid": 0,
    "lessonsValidPercent": 0,
    "missingEvalRecords": "لا تظهر سجلات في ملفي النشاط",
    "missingLessonRecords": "لا تظهر سجلات في ملفي النشاط",
    "notes": "التقدير المعتمد: جيد جداً في الدروس وجيد جداً في التقييمات. تقدير إداري للمعلمين ضمن النطاق دون بيانات نشاط متاحة.",
    "category": "top_aspect",
    "badges": [
      "التقدير المعتمد: جيد جداً 🎖️",
      "ضمن نطاق التقرير الإداري"
    ],
    "adminRating": "جيد جداً",
    "adminRatingBasis": "تقدير إداري للمعلمين ضمن النطاق دون بيانات نشاط متاحة",
    "hasActivityData": false
  }
];

export const TOP_OVERALL_TEACHERS = SEPTEMBER_2026_LMS_TEACHERS.filter(t => t.category === 'top_overall' || (t.generalIndex && t.generalIndex >= 80));
export const TOP_DEPT_TEACHERS = SEPTEMBER_2026_LMS_TEACHERS.filter(t => t.category === 'top_dept' || t.bestInDept);
export const TOP_LESSONS_TEACHERS = [...SEPTEMBER_2026_LMS_TEACHERS].filter(t => t.lessonsUploaded > 0).sort((a, b) => b.lessonsValid - a.lessonsValid).slice(0, 10);
export const TOP_GRADED_TEACHERS = [...SEPTEMBER_2026_LMS_TEACHERS].filter(t => t.submissionsReceived > 0).sort((a, b) => b.submissionsGraded - a.submissionsGraded).slice(0, 10);

export const FOLLOWUP_PENDING_TEACHERS = SEPTEMBER_2026_LMS_TEACHERS.filter(t => t.submissionsPending > 0).sort((a, b) => b.submissionsPending - a.submissionsPending);
export const FOLLOWUP_PARTIAL_TEACHERS = SEPTEMBER_2026_LMS_TEACHERS.filter(t => t.evalCoveragePercent > 0 && t.evalCoveragePercent < 100);
export const UNASSIGNED_EVAL_TEACHERS = SEPTEMBER_2026_LMS_TEACHERS.filter(t => t.evalUnassigned > 0);
export const ZERO_LESSON_TEACHERS = SEPTEMBER_2026_LMS_TEACHERS.filter(t => t.hasActivityData && t.lessonsUploaded === 0);


export function generateSeptember2026Evaluations(teachers: any[]): any[] {
  const out: any[] = [];
  let eIdx = 9000;

  SEPTEMBER_2026_LMS_TEACHERS.forEach(lmsT => {
    const t = teachers.find(x => 
      x.nameAr === lmsT.name || 
      x.nameAr.includes(lmsT.name) || 
      lmsT.name.includes(x.nameAr) ||
      (x.nameEn && lmsT.name.toLowerCase().includes(x.nameEn.toLowerCase()))
    );
    if (!t) return;

    let totalScore = 80;
    let perfLabel = 'جيد جداً';

    if (lmsT.adminRating === 'ممتاز') {
      totalScore = 96;
      perfLabel = 'ممتاز';
    } else if (lmsT.adminRating === 'جيد جداً') {
      totalScore = 86;
      perfLabel = 'جيد جداً';
    } else if (lmsT.generalIndex) {
      totalScore = Math.round(lmsT.generalIndex * 10) / 10;
      perfLabel = totalScore >= 90 ? 'ممتاز' : totalScore >= 80 ? 'جيد جداً' : totalScore >= 70 ? 'جيد' : 'يحتاج إلى متابعة وخطة تحسين';
    } else if (lmsT.hasActivityData) {
      const c = (lmsT.evalCoveragePercent * 0.3) + (lmsT.gradingRate * 0.25) + (lmsT.solveRate * 0.2) + (lmsT.lessonsValidPercent * 0.25);
      totalScore = Math.max(60, Math.min(100, Math.round(c * 10) / 10));
      perfLabel = totalScore >= 90 ? 'ممتاز' : totalScore >= 80 ? 'جيد جداً' : totalScore >= 70 ? 'جيد' : 'يحتاج إلى متابعة وخطة تحسين';
    }

    const avgScore = Math.round((totalScore / 5) * 10) / 10;
    const critScore = Math.round((totalScore / 5) * 10) / 10;

    const criteria = [
      { score: critScore, note: 'الدروس: ' + lmsT.lessonsUploaded + ' مرفوعة (' + lmsT.lessonsValid + ' مستوفية)' },
      { score: critScore, note: 'تغطية التقييمات: ' + lmsT.evalCoverageRatio + ' (' + lmsT.evalCoveragePercent + '%)' },
      { score: critScore, note: 'التصحيح: ' + lmsT.submissionsGraded + '/' + lmsT.submissionsReceived + ' (' + lmsT.gradingRate + '%)' },
      { score: critScore >= 14 ? 20 : 0, note: lmsT.evalUploaded > 0 ? 'تم إسناد التقييمات' : 'متابعة إسناد التقييمات' },
      { score: critScore, note: 'نسبة الحل: ' + lmsT.solveRate + '%' },
      { score: 0, note: lmsT.notes, value: 'نعم' }
    ];

    out.push({
      id: 'lms_ev_' + (eIdx++),
      teacherId: t.id,
      evaluatorId: 'u1',
      month: 'سبتمبر',
      academicYear: '2026-2027',
      term: 'الفصل الأول',
      evaluationDate: '2026-09-20',
      criteria,
      totalScore,
      averageScore: avgScore,
      percentage: totalScore,
      performanceLevel: perfLabel,
      strengths: lmsT.badges.join(' • ') || 'متابعة النشاط على المنصة وفق المؤشرات الرسمية',
      improvementAreas: lmsT.submissionsPending > 0 ? ('استكمال تصحيح ' + lmsT.submissionsPending + ' تسليماً معلقاً') : 'الاستمرار في الحفاظ على هذا المستوى المتميز',
      recommendations: lmsT.notes,
      actionPlan: lmsT.submissionsPending > 0 ? 'متابعة تصحيح التسليمات المتأخرة والتحقق من التقييمات' : '',
      hasWeeklyAssignment: lmsT.evalUploaded > 0,
      evidenceLinks: [],
      generalNotes: lmsT.notes,
      createdAt: '2026-09-20T10:00:00Z',
      updatedAt: '2026-09-20T10:00:00Z',
    });
  });

  return out;
}

