export const SEED_TASKS = [
  // August 2025
  { "month": "أغسطس", "academicYear": "2025-2026", "taskDate": "2025-08-01", "category": "الاجتماعات", "title": "تشكيل فريق رواد التعليم الالكتروني وعقد الاجتماع", "status": "مكتملة", "evidenceLabel": "Click Here", "evidenceUrl": "https://educationqa-my.sharepoint.com/:b:/g/personal/a_tubaishat1704_education_qa/ERiqFQcmZOxAvjmN-RR4B7YBm4LxDWISPrLZua0GQNAXZQ?e=mggKmq", "sourceSheet": "Aug", "sourceRow": 5, "hasEvidence": true, "completionPercentage": 100, "evidenceStatus": "يوجد دليل إنجاز", "priority": "متوسطة", "taskType": "شهرية", "source": "تقرير المهام الشهرية.xlsx" },
  { "month": "أغسطس", "academicYear": "2025-2026", "taskDate": "2025-08-01", "category": "الاجتماعات", "title": "اجتماع النائب الأكاديمي الأول لسنة ٢٠٢٥-٢٠٢٦م", "status": "مكتملة", "evidenceLabel": "Click Here", "evidenceUrl": "https://educationqa-my.sharepoint.com/:b:/g/personal/a_tubaishat1704_education_qa/ESmBo6hauGBNsDpkLp8BS3QBu-9x6HOl5aOLk99mLmeRcw?e=nwIKK5", "sourceSheet": "Aug", "sourceRow": 6, "hasEvidence": true, "completionPercentage": 100, "evidenceStatus": "يوجد دليل إنجاز", "priority": "متوسطة", "taskType": "شهرية", "source": "تقرير المهام الشهرية.xlsx" },
  { "month": "أغسطس", "academicYear": "2025-2026", "taskDate": "2025-08-01", "category": "الاجتماعات", "title": "اجتماع التحصيل الأكاديمي واجتماع لجنة الدراسة الذاتية", "status": "مكتملة", "evidenceLabel": "Done", "evidenceUrl": "", "sourceSheet": "Aug", "sourceRow": 7, "hasEvidence": false, "completionPercentage": 100, "priority": "متوسطة", "taskType": "شهرية", "source": "تقرير المهام الشهرية.xlsx" },
  { "month": "أغسطس", "academicYear": "2025-2026", "taskDate": "2025-08-01", "category": "الاجتماعات", "title": "عقد ورشة تدريبية للموظفين الجدد (إداري – معلم) ضمن خطة التطوير المهني", "status": "مكتملة", "evidenceLabel": "Click here", "evidenceUrl": "https://educationqa-my.sharepoint.com/:b:/g/personal/a_tubaishat1704_education_qa/ESdY473MjOdEhUIey_tNjwIB7_5RgyQjWQ-C3LlsyPqQOQ?e=XcRj6Y", "sourceSheet": "Aug", "sourceRow": 8, "hasEvidence": true, "completionPercentage": 100, "evidenceStatus": "يوجد دليل إنجاز", "priority": "متوسطة", "taskType": "شهرية", "source": "تقرير المهام الشهرية.xlsx" },
  { "month": "أغسطس", "academicYear": "2025-2026", "taskDate": "2025-08-01", "category": "التطوير المهني", "title": "متابعة المعلمين لحضور ورش التطوير المهني Edpuzzle Online واعداد تقرير الورش ورفعه للأرشفة الالكترونية", "status": "مكتملة", "evidenceLabel": "Click Here", "evidenceUrl": "https://educationqa-my.sharepoint.com/:w:/g/personal/a_tubaishat1704_education_qa/ERNHBy94zTlAh57c4Ot2z2sBldwVxKJfEXcOSxbmUf0fZg?e=p1hSlc", "sourceSheet": "Aug", "sourceRow": 10, "hasEvidence": true, "completionPercentage": 100, "evidenceStatus": "يوجد دليل إنجاز", "priority": "متوسطة", "taskType": "شهرية", "source": "تقرير المهام الشهرية.xlsx" },
  { "month": "أغسطس", "academicYear": "2025-2026", "taskDate": "2025-08-01", "category": "التطوير المهني", "title": "التنسيق واعداد تقرير ورشة Classpoint", "status": "مكتملة", "evidenceLabel": "Click Here", "evidenceUrl": "https://educationqa-my.sharepoint.com/:w:/g/personal/a_tubaishat1704_education_qa/EfeY3xuUtdZNiu_1_fY7VeEB6I4bSA2q24aUrq73qVm4dw?e=JNknvo", "sourceSheet": "Aug", "sourceRow": 11, "hasEvidence": true, "completionPercentage": 100, "evidenceStatus": "يوجد دليل إنجاز", "priority": "متوسطة", "taskType": "شهرية", "source": "تقرير المهام الشهرية.xlsx" },
  { "month": "أغسطس", "academicYear": "2025-2026", "taskDate": "2025-08-01", "category": "التطوير المهني", "title": "اعداد ورشة تذكيرية لنظام قطر للتعليم", "status": "مكتملة", "evidenceLabel": "Click Here", "evidenceUrl": "https://educationqa-my.sharepoint.com/:b:/g/personal/a_tubaishat1704_education_qa/EXneb9mLsxFFuwncbomzY7cB4mmSElwEulwsdpOdEwFeuQ?e=e6YvH6", "sourceSheet": "Aug", "sourceRow": 12, "hasEvidence": true, "completionPercentage": 100, "evidenceStatus": "يوجد دليل إنجاز", "priority": "متوسطة", "taskType": "شهرية", "source": "تقرير المهام الشهرية.xlsx" },
  { "month": "أغسطس", "academicYear": "2025-2026", "taskDate": "2025-08-01", "category": "التطوير المهني", "title": "اعداد تقرير ورشة VR", "status": "مكتملة", "evidenceLabel": "Click Here", "evidenceUrl": "https://educationqa-my.sharepoint.com/:b:/g/personal/a_tubaishat1704_education_qa/ERTgTwKJq6FJryfHsBw5jo4B0jyDvfGHr59hL-CMHBRA6A?e=g1uWB3", "sourceSheet": "Aug", "sourceRow": 13, "hasEvidence": true, "completionPercentage": 100, "evidenceStatus": "يوجد دليل إنجاز", "priority": "متوسطة", "taskType": "شهرية", "source": "تقرير المهام الشهرية.xlsx" },
  { "month": "أغسطس", "academicYear": "2025-2026", "taskDate": "2025-08-01", "category": "التطوير المهني", "title": "انشاء استبيان حصر الاحتياجات التدريبية", "status": "مكتملة", "evidenceLabel": "Click Here", "evidenceUrl": "https://educationqa-my.sharepoint.com/:x:/g/personal/a_tubaishat1704_education_qa/EX-w83Fgo-lLtsMbQDTfy4ABhCJviNEGX4jOrApmC7kQvw?e=bI2eXH", "sourceSheet": "Aug", "sourceRow": 14, "hasEvidence": true, "completionPercentage": 100, "evidenceStatus": "يوجد دليل إنجاز", "priority": "متوسطة", "taskType": "شهرية", "source": "تقرير المهام الشهرية.xlsx" },
  { "month": "أغسطس", "academicYear": "2025-2026", "taskDate": "2025-08-01", "category": "التطوير المهني", "title": "ورش جماعية وفردية حول آخر إرشادات التعليم الإلكتروني بخصوص: نشر الدروس، التقييمات، نظام قطر للتعليم", "status": "مكتملة", "evidenceLabel": "Click Here", "evidenceUrl": "https://educationqa-my.sharepoint.com/:b:/g/personal/a_tubaishat1704_education_qa/EcrA8E5VXpFAs5XV5pC5su4BzJMfwx8X_2PXFO-VOPDTyw?e=ABdS1L", "sourceSheet": "Aug", "sourceRow": 15, "hasEvidence": true, "completionPercentage": 100, "evidenceStatus": "يوجد دليل إنجاز", "priority": "متوسطة", "taskType": "شهرية", "source": "تقرير المهام الشهرية.xlsx" },
  { "month": "أغسطس", "academicYear": "2025-2026", "taskDate": "2025-08-01", "category": "التخطيط والمتابعة", "title": "الانتهاء من تجهيزات المعلمين والطلاب الجدد: توفير الأجهزة، إنشاء الحسابات الإلكترونية، أي تجهيزات داعمة", "status": "مكتملة", "evidenceLabel": "Done", "evidenceUrl": "", "sourceSheet": "Aug", "sourceRow": 17, "hasEvidence": false, "completionPercentage": 100, "priority": "متوسطة", "taskType": "شهرية", "source": "تقرير المهام الشهرية.xlsx" },
  { "month": "أغسطس", "academicYear": "2025-2026", "taskDate": "2025-08-01", "category": "التخطيط والمتابعة", "title": "إنشاء قنوات Microsoft Teams: قنوات الصفوف الدراسية والقنوات الإدارية", "status": "مكتملة", "evidenceLabel": "Done", "evidenceUrl": "", "sourceSheet": "Aug", "sourceRow": 18, "hasEvidence": false, "completionPercentage": 100, "priority": "متوسطة", "taskType": "شهرية", "source": "تقرير المهام الشهرية.xlsx" },
  { "month": "أغسطس", "academicYear": "2025-2026", "taskDate": "2025-08-01", "category": "التخطيط والمتابعة", "title": "نشر الأدلة الإرشادية: دليل ولي الأمر ودليل الموظفين عبر البريد الإلكتروني والرسائل النصية", "status": "مكتملة", "evidenceLabel": "Click Here", "evidenceUrl": "https://educationqa-my.sharepoint.com/:f:/g/personal/a_tubaishat1704_education_qa/EvkVDlSOeYZAvnUZ-tYV980BXFmjmOEX3XCGekoJhZnnGQ?e=n0AQXO", "sourceSheet": "Aug", "sourceRow": 19, "hasEvidence": true, "completionPercentage": 100, "evidenceStatus": "يوجد دليل إنجاز", "priority": "متوسطة", "taskType": "شهرية", "source": "تقرير المهام الشهرية.xlsx" },
  { "month": "أغسطس", "academicYear": "2025-2026", "taskDate": "2025-08-01", "category": "التخطيط والمتابعة", "title": "توزيع ميثاق التعهد للاستخدام الآمن للتكنولوجيا لجميع الطلاب والموظفين والتأكد من التوقيع والاستلام للجيمع الطلاب", "status": "مكتملة", "evidenceLabel": "Click Here", "evidenceUrl": "https://educationqa-my.sharepoint.com/:b:/g/personal/a_tubaishat1704_education_qa/ESxqww0zETFElOm4HMmOPPwBRgrsPyrRoXGDewI5Y1xYFQ?e=18IYu3", "sourceSheet": "Aug", "sourceRow": 20, "hasEvidence": true, "completionPercentage": 100, "evidenceStatus": "يوجد دليل إنجاز", "priority": "متوسطة", "taskType": "شهرية", "source": "تقرير المهام الشهرية.xlsx" },
  { "month": "أغسطس", "academicYear": "2025-2026", "taskDate": "2025-08-01", "category": "التخطيط والمتابعة", "title": "انشاء واعداد خطط التعليم الالكتروني وخطط العمل اللازمة لبداية العام الأكاديمي الجديد:التطوير المهني-الارشادية-SWOT..", "status": "مكتملة", "evidenceLabel": "Click Here", "evidenceUrl": "https://educationqa-my.sharepoint.com/:f:/g/personal/a_tubaishat1704_education_qa/EqpdWGUHNLRNueU2RePdYB0BzCN7zmLhY0x30Q9mg2vHyg?e=Ll05BE", "sourceSheet": "Aug", "sourceRow": 21, "hasEvidence": true, "completionPercentage": 100, "evidenceStatus": "يوجد دليل إنجاز", "priority": "متوسطة", "taskType": "شهرية", "source": "تقرير المهام الشهرية.xlsx" },
  { "month": "أغسطس", "academicYear": "2025-2026", "taskDate": "2025-08-01", "category": "التخطيط والمتابعة", "title": "انشاء سياسة الذكاء الاصطناعي للطلاب والمعلمين وتعميمها", "status": "مكتملة", "evidenceLabel": "Click Here", "evidenceUrl": "https://educationqa-my.sharepoint.com/:f:/g/personal/a_tubaishat1704_education_qa/En1jvBIGeDpBphpUu8_oJYoB5A7J5nraUZwpW_tqpAQOKg?e=4IOHHn", "sourceSheet": "Aug", "sourceRow": 22, "hasEvidence": true, "completionPercentage": 100, "evidenceStatus": "يوجد دليل إنجاز", "priority": "متوسطة", "taskType": "شهرية", "source": "تقرير المهام الشهرية.xlsx" },
  { "month": "أغسطس", "academicYear": "2025-2026", "taskDate": "2025-08-01", "category": "التخطيط والمتابعة", "title": "انشاء دليل الأنظمة والمنصات الالكترونية التعليمية للمدرسة", "status": "مكتملة", "evidenceLabel": "Click Here", "evidenceUrl": "https://educationqa-my.sharepoint.com/:b:/g/personal/a_tubaishat1704_education_qa/ESgSHmH58gFAmEPxrWNnW40B3RIvs0pALQDkzNLIqqbreQ?e=qFj17e", "sourceSheet": "Aug", "sourceRow": 23, "hasEvidence": true, "completionPercentage": 100, "evidenceStatus": "يوجد دليل إنجاز", "priority": "متوسطة", "taskType": "شهرية", "source": "تقرير المهام الشهرية.xlsx" },
  { "month": "أغسطس", "academicYear": "2025-2026", "taskDate": "2025-08-01", "category": "التخطيط والمتابعة", "title": "انشاء ميثاق التعهد الامن لاستخدام التكنولوجيا", "status": "مكتملة", "evidenceLabel": "Click Here", "evidenceUrl": "https://educationqa-my.sharepoint.com/:b:/g/personal/a_tubaishat1704_education_qa/ESHoxnD-zrVFh0z1ZeiLjzMBhmP911EEAUHKT92Nus-xUQ?e=4fCw5q", "sourceSheet": "Aug", "sourceRow": 24, "hasEvidence": true, "completionPercentage": 100, "evidenceStatus": "يوجد دليل إنجاز", "priority": "متوسطة", "taskType": "شهرية", "source": "تقرير المهام الشهرية.xlsx" },
  { "month": "أغسطس", "academicYear": "2025-2026", "taskDate": "2025-08-01", "category": "التخطيط والمتابعة", "title": "اعداد ملفات التعليم الالكتروني ٢٠٢٥-٢٠٢٦ م", "status": "مكتملة", "evidenceLabel": "Click Here", "evidenceUrl": "https://educationqa-my.sharepoint.com/:f:/g/personal/a_tubaishat1704_education_qa/EjReSN2-VsJJgKMEOZyEBaYBFIOzVzkxJEuA_DWr9BKT4Q?e=nQwxrq", "sourceSheet": "Aug", "sourceRow": 25, "hasEvidence": true, "completionPercentage": 100, "evidenceStatus": "يوجد دليل إنجاز", "priority": "متوسطة", "taskType": "شهرية", "source": "تقرير المهام الشهرية.xlsx" },
  { "month": "أغسطس", "academicYear": "2025-2026", "taskDate": "2025-08-01", "category": "التخطيط والمتابعة", "title": "انشاء بوستر كتاب ستيم التاسع و العاشر والتنسيق مع الطباعه لنشره على الكتب والدفاتر", "status": "مكتملة", "evidenceLabel": "Click Here", "evidenceUrl": "https://educationqa-my.sharepoint.com/:f:/g/personal/a_tubaishat1704_education_qa/EmW6lxUdDzFHsV81HzIrSScBOifu5iwbTt3h3tpPrm-m2A?e=MdtSh9", "sourceSheet": "Aug", "sourceRow": 26, "hasEvidence": true, "completionPercentage": 100, "evidenceStatus": "يوجد دليل إنجاز", "priority": "متوسطة", "taskType": "شهرية", "source": "تقرير المهام الشهرية.xlsx" },
  { "month": "أغسطس", "academicYear": "2025-2026", "taskDate": "2025-08-01", "category": "التخطيط والمتابعة", "title": "انشاء الدليل الارشادي لتفعيل الخدمات الإلكترونية للموظفين", "status": "مكتملة", "evidenceLabel": "Click Here", "evidenceUrl": "https://dimensions-eb.my.canva.site/qstssemployees", "sourceSheet": "Aug", "sourceRow": 27, "hasEvidence": true, "completionPercentage": 100, "evidenceStatus": "يوجد دليل إنجاز", "priority": "متوسطة", "taskType": "شهرية", "source": "تقرير المهام الشهرية.xlsx" },
  { "month": "أغسطس", "academicYear": "2025-2026", "taskDate": "2025-08-01", "category": "التخطيط والمتابعة", "title": "انشاء الدليل الإرشادي لتفعيل الخدمات الالكترونية لولي الأمر", "status": "مكتملة", "evidenceLabel": "Click Here", "evidenceUrl": "https://new.express.adobe.com/webpage/pt8RAJ4e6CIzU", "sourceSheet": "Aug", "sourceRow": 28, "hasEvidence": true, "completionPercentage": 100, "evidenceStatus": "يوجد دليل إنجاز", "priority": "متوسطة", "taskType": "شهرية", "source": "تقرير المهام الشهرية.xlsx" },
  { "month": "أغسطس", "academicYear": "2025-2026", "taskDate": "2025-08-01", "category": "التخطيط والمتابعة", "title": "انشاء جداول حصص التلعيم الالكتروني", "status": "مكتملة", "evidenceLabel": "Click Here", "evidenceUrl": "https://educationqa-my.sharepoint.com/:x:/g/personal/a_tubaishat1704_education_qa/EQmFe8inq6hDqAjdgbY2QFwBtb4vF-s2mSwdTATl94lY_Q?e=LkRSbU", "sourceSheet": "Aug", "sourceRow": 29, "hasEvidence": true, "completionPercentage": 100, "evidenceStatus": "يوجد دليل إنجاز", "priority": "متوسطة", "taskType": "شهرية", "source": "تقرير المهام الشهرية.xlsx" },
  { "month": "أغسطس", "academicYear": "2025-2026", "taskDate": "2025-08-01", "category": "التخطيط والمتابعة", "title": "انشاء ملفات الاعتماد الوطني الخاص بالمدرسة : بيئة التعلم", "status": "مكتملة", "evidenceLabel": "Click Here", "evidenceUrl": "https://educationqa-my.sharepoint.com/:b:/g/personal/a_tubaishat1704_education_qa/EU2JDRlCKxtCsIZZu5mbNC8BZV7dxjaWnuhb5jiKOfsj4g?e=GLw5Tl", "sourceSheet": "Aug", "sourceRow": 30, "hasEvidence": true, "completionPercentage": 100, "evidenceStatus": "يوجد دليل إنجاز", "priority": "متوسطة", "taskType": "شهرية", "source": "تقرير المهام الشهرية.xlsx" },
  { "month": "أغسطس", "academicYear": "2025-2026", "taskDate": "2025-08-01", "category": "التخطيط والمتابعة", "title": "انشاء فيديو ارشادي لولي الامر - نظام قطر للتعليم", "status": "مكتملة", "evidenceLabel": "Click Here", "evidenceUrl": "https://educationqa-my.sharepoint.com/:v:/g/personal/a_tubaishat1704_education_qa/EQlKJd-JHLRBtZFqw00nSUcB7MWaG4mEt0cH5h-R1d_RuQ?e=FO9RMy", "sourceSheet": "Aug", "sourceRow": 31, "hasEvidence": true, "completionPercentage": 100, "evidenceStatus": "يوجد دليل إنجاز", "priority": "متوسطة", "taskType": "شهرية", "source": "تقرير المهام الشهرية.xlsx" },
  { "month": "أغسطس", "academicYear": "2025-2026", "taskDate": "2025-08-01", "category": "التخطيط والمتابعة", "title": "انشاء تقرير مختبر الواقع الافتراضي", "status": "مكتملة", "evidenceLabel": "Click Here", "evidenceUrl": "https://educationqa-my.sharepoint.com/:b:/g/personal/a_tubaishat1704_education_qa/ESyYKJ8mJRlJqwMuM3ZXS3gBypPe7xu46E5rd3rjKBvHDw?e=2yTu3W", "sourceSheet": "Aug", "sourceRow": 32, "hasEvidence": true, "completionPercentage": 100, "evidenceStatus": "يوجد دليل إنجاز", "priority": "متوسطة", "taskType": "شهرية", "source": "تقرير المهام الشهرية.xlsx" },
  { "month": "أغسطس", "academicYear": "2025-2026", "taskDate": "2025-08-01", "category": "التخطيط والمتابعة", "title": "انشاء التقرير السنوي لتفعيل الخدمات التكنوولجية لسنة ٢٠٢٤-٢٠٢٥م", "status": "مكتملة", "evidenceLabel": "Click Here", "evidenceUrl": "https://educationqa-my.sharepoint.com/:b:/g/personal/a_tubaishat1704_education_qa/ES7_OkfxJIdCve8ipSQPyHoBRcPVcJvIUwS6MXhhaOz2aA?e=cb2hWA", "sourceSheet": "Aug", "sourceRow": 33, "hasEvidence": true, "completionPercentage": 100, "evidenceStatus": "يوجد دليل إنجاز", "priority": "متوسطة", "taskType": "شهرية", "source": "تقرير المهام الشهرية.xlsx" },
  
  // September 2025
  { "month": "سبتمبر", "academicYear": "2025-2026", "taskDate": "2025-09-01", "category": "الاجتماعات", "title": "اجتماع التحصيل الاكاديمي الثاني", "status": "مكتملة", "evidenceLabel": "Click Here", "evidenceUrl": "https://educationqa-my.sharepoint.com/:b:/g/personal/a_tubaishat1704_education_qa/EZCxYIEmO1dMg6s3wottSTkB6uVLAx87IydNl1TzxtMKyw?e=OImlff", "sourceSheet": "Sep", "sourceRow": 5, "hasEvidence": true, "completionPercentage": 100, "evidenceStatus": "يوجد دليل إنجاز", "priority": "متوسطة", "taskType": "شهرية", "source": "تقرير المهام الشهرية.xlsx" },
  { "month": "سبتمبر", "academicYear": "2025-2026", "taskDate": "2025-09-01", "category": "التطوير المهني", "title": "عقد ورش فردية لمعلمي المدرسة في نظام قطر للتعليم و الذكاء الاصطناعي و كانفا وغيرها", "status": "مكتملة", "evidenceLabel": "Click Here", "evidenceUrl": "https://educationqa-my.sharepoint.com/:b:/g/personal/a_tubaishat1704_education_qa/EWYX4_V3xrxMvNLws7lI438B3AbQoAr6KirpNyPcwLiq8Q?e=mfFfOD", "sourceSheet": "Sep", "sourceRow": 15, "hasEvidence": true, "completionPercentage": 100, "evidenceStatus": "يوجد دليل إنجاز", "priority": "متوسطة", "taskType": "شهرية", "source": "تقرير المهام الشهرية.xlsx" },
  { "month": "سبتمبر", "academicYear": "2025-2026", "taskDate": "2025-09-01", "category": "التخطيط والمتابعة", "title": "متابعة حصص التعليم الالكتروني للمعلمين و نشر الجدول لهم وكتابة التقارير للحصص وماشركة التقرير", "status": "مكتملة", "evidenceLabel": "Click Here", "evidenceUrl": "https://educationqa-my.sharepoint.com/:x:/g/personal/a_tubaishat1704_education_qa/EQmFe8inq6hDqAjdgbY2QFwBtb4vF-s2mSwdTATl94lY_Q?e=mRCbPz", "sourceSheet": "Sep", "sourceRow": 27, "hasEvidence": true, "completionPercentage": 100, "evidenceStatus": "يوجد دليل إنجاز", "priority": "متوسطة", "taskType": "شهرية", "source": "تقرير المهام الشهرية.xlsx" },
  
  // October 2025
  { "month": "أكتوبر", "academicYear": "2025-2026", "taskDate": "2025-10-01", "category": "الاجتماعات", "title": "اجتماع أولياء الأمور الأول مع اداره المدرسة", "status": "مكتملة", "evidenceLabel": "Click Here", "evidenceUrl": "https://educationqa-my.sharepoint.com/:f:/g/personal/a_tubaishat1704_education_qa/EhMYx26nJv9NpC9lBoJVGH0BpUu25B9zuDQMLcorDqVXCw?e=JQA1nG", "sourceSheet": "Oct", "sourceRow": 5, "hasEvidence": true, "completionPercentage": 100, "evidenceStatus": "يوجد دليل إنجاز", "priority": "متوسطة", "taskType": "شهرية", "source": "تقرير المهام الشهرية.xlsx" },

  // November 2025
  { "month": "نوفمبر", "academicYear": "2025-2026", "taskDate": "2025-11-01", "category": "الاجتماعات", "title": "جلسة تعريفية بمشروع مبدعون في التعليم", "status": "يوجد دليل إنجاز", "evidenceLabel": "Click Here", "evidenceUrl": "https://educationqa-my.sharepoint.com/:f:/g/personal/a_tubaishat1704_education_qa/EhMYx26nJv9NpC9lBoJVGH0BpUu25B9zuDQMLcorDqVXCw?e=JQA1nG", "source": "تقارير المهام الشهرية - نوفمبر 2025", "hasEvidence": true, "completionPercentage": 100, "priority": "متوسطة", "taskType": "شهرية", "createdBy": "E-Projects Coordinator" },
  { "month": "نوفمبر", "academicYear": "2025-2026", "taskDate": "2025-11-01", "category": "الاجتماعات", "title": "اجتماع أولياء الأمور الثاني - حضوري في المدرسة الساعة ٥ مساءا", "status": "مكتملة", "evidenceLabel": "Done", "evidenceUrl": "", "source": "تقارير المهام الشهرية - نوفمبر 2025", "hasEvidence": false, "completionPercentage": 100, "priority": "متوسطة", "taskType": "شهرية", "createdBy": "E-Projects Coordinator" },
  { "month": "نوفمبر", "academicYear": "2025-2026", "taskDate": "2025-11-01", "category": "الاجتماعات", "title": "اجتماع التحصيل الاكاديمي", "status": "مكتملة", "evidenceLabel": "Done", "evidenceUrl": "", "source": "تقارير المهام الشهرية - نوفمبر 2025", "hasEvidence": false, "completionPercentage": 100, "priority": "متوسطة", "taskType": "شهرية", "createdBy": "E-Projects Coordinator" },
  { "month": "نوفمبر", "academicYear": "2025-2026", "taskDate": "2025-11-01", "category": "الاجتماعات", "title": "اجتماع مع وفد المدرسة الخضراء وشركة Seabearch", "status": "مكتملة", "evidenceLabel": "Done", "evidenceUrl": "", "source": "تقارير المهام الشهرية - نوفمبر 2025", "hasEvidence": false, "completionPercentage": 100, "priority": "متوسطة", "taskType": "شهرية", "createdBy": "E-Projects Coordinator" },
  { "month": "نوفمبر", "academicYear": "2025-2026", "taskDate": "2025-11-01", "category": "الاجتماعات", "title": "تبادل خبرات مع مدرسة الشمال الثانوية للبنين - زيارة للمدرسة", "status": "يوجد دليل إنجاز", "evidenceLabel": "Click Here", "evidenceUrl": "https://educationqa-my.sharepoint.com/:b:/g/personal/a_tubaishat1704_education_qa/IQCjPb1SzuRZT6qfUnGw3sbkAZ8RKueZC0LJe12Et2L16S8?e=czOcHP", "source": "تقارير المهام الشهرية - نوفمبر 2025", "hasEvidence": true, "completionPercentage": 100, "priority": "متوسطة", "taskType": "شهرية", "createdBy": "E-Projects Coordinator" },
  { "month": "نوفمبر", "academicYear": "2025-2026", "taskDate": "2025-11-01", "category": "التطوير المهني", "title": "محاضرة توعوية حول التنمّر الإلكتروني في المسرح المدرسي لطلاب الصف التاسع", "status": "يوجد دليل إنجاز", "evidenceLabel": "Click Here", "evidenceUrl": "https://educationqa-my.sharepoint.com/:f:/g/personal/a_tubaishat1704_education_qa/En-eLoNAw1tOj_rWUd-nMZMBBzu-9VNel0QppMyNr5mR8g?e=r0XCbW", "source": "تقارير المهام الشهرية - نوفمبر 2025", "hasEvidence": true, "completionPercentage": 100, "priority": "متوسطة", "taskType": "شهرية", "createdBy": "E-Projects Coordinator" },
  { "month": "نوفمبر", "academicYear": "2025-2026", "taskDate": "2025-11-01", "category": "التخطيط والمتابعة", "title": "التخطيط والتنظيم ليوم التعلم عن بعد", "status": "يوجد دليل إنجاز", "evidenceLabel": "Click Here", "evidenceUrl": "https://educationqa-my.sharepoint.com/:f:/g/personal/a_tubaishat1704_education_qa/Er-EGft1NeFIm9lp7P9t2wIB9cfxRHCxKLLfiFLFF9bwvQ?e=3vsgcM", "source": "تقارير المهام الشهرية - نوفمبر 2025", "hasEvidence": true, "completionPercentage": 100, "priority": "متوسطة", "taskType": "شهرية", "createdBy": "E-Projects Coordinator" },
  { "month": "نوفمبر", "academicYear": "2025-2026", "taskDate": "2025-11-01", "category": "التخطيط والمتابعة", "title": "التخطيط والتنظيم والتنسيق والتدريب لمسابقة المهارات الخليجية آسيا 2025 - تايوان", "status": "مكتملة", "evidenceLabel": "DONE", "evidenceUrl": "", "source": "تقارير المهام الشهرية - نوفمبر 2025", "hasEvidence": false, "completionPercentage": 100, "priority": "متوسطة", "taskType": "شهرية", "createdBy": "E-Projects Coordinator" },
  { "month": "نوفمبر", "academicYear": "2025-2026", "taskDate": "2025-11-01", "category": "التخطيط والمتابعة", "title": "إعداد تقرير يوم التعلم عن بعد", "status": "يوجد دليل إنجاز", "evidenceLabel": "Click Here", "evidenceUrl": "https://educationqa-my.sharepoint.com/:b:/g/personal/a_tubaishat1704_education_qa/IQCWI8o5dAtXRYLFiH_R-DysAUQfhCK6RZeXnf4DfBPPxoU?e=26VCdk", "source": "تقارير المهام الشهرية - نوفمبر 2025", "hasEvidence": true, "completionPercentage": 100, "priority": "متوسطة", "taskType": "شهرية", "createdBy": "E-Projects Coordinator" },
  { "month": "نوفمبر", "academicYear": "2025-2026", "taskDate": "2025-11-01", "category": "التخطيط والمتابعة", "title": "إعداد تقرير شهر نوفمبر لمنصة قطر للتعليم", "status": "يوجد دليل إنجاز", "evidenceLabel": "Click Here", "evidenceUrl": "https://educationqa-my.sharepoint.com/:b:/g/personal/a_tubaishat1704_education_qa/IQDg74IT6NKoQ5lR2kXxkVwrAaRJFhMCOy6BtZaOTfh5leE?e=QBtvgc", "source": "تقارير المهام الشهرية - نوفمبر 2025", "hasEvidence": true, "completionPercentage": 100, "priority": "متوسطة", "taskType": "شهرية", "createdBy": "E-Projects Coordinator" },
  { "month": "نوفمبر", "academicYear": "2025-2026", "taskDate": "2025-11-01", "category": "التخطيط والمتابعة", "title": "إجراءات توفير متطلبات مدارس العلوم والتكنولوجيا الجديدة", "status": "مكتملة", "evidenceLabel": "Done", "evidenceUrl": "", "source": "تقارير المهام الشهرية - نوفمبر 2025", "hasEvidence": false, "completionPercentage": 100, "priority": "متوسطة", "taskType": "شهرية", "createdBy": "E-Projects Coordinator" },
  { "month": "نوفمبر", "academicYear": "2025-2026", "taskDate": "2025-11-01", "category": "التخطيط والمتابعة", "title": "إعداد تقارير حصص التعليم الإلكتروني", "status": "يوجد دليل إنجاز", "evidenceLabel": "Click Here", "evidenceUrl": "https://educationqa-my.sharepoint.com/:f:/g/personal/a_tubaishat1704_education_qa/IgD08ZXr_xa-RI8robC_3bnKAcK4tdnj1mcouxcWHAMjvSI?e=SPz3Lh", "source": "تقارير المهام الشهرية - نوفمبر 2025", "hasEvidence": true, "completionPercentage": 100, "priority": "متوسطة", "taskType": "شهرية", "createdBy": "E-Projects Coordinator" },
  { "month": "نوفمبر", "academicYear": "2025-2026", "taskDate": "2025-11-01", "category": "التخطيط والمتابعة", "title": "إعداد تقارير التعليم الإلكتروني للنائب الأكاديمي", "status": "يوجد دليل إنجاز", "evidenceLabel": "Click Here", "evidenceUrl": "https://educationqa-my.sharepoint.com/:f:/g/personal/a_tubaishat1704_education_qa/IgB94QQ_DnCcSbh__emWM0_RARfM4UIbBQoyNOSrwozAyac?e=Ycf7Hy", "source": "تقارير المهام الشهرية - نوفمبر 2025", "hasEvidence": true, "completionPercentage": 100, "priority": "متوسطة", "taskType": "شهرية", "createdBy": "E-Projects Coordinator" },
  { "month": "نوفمبر", "academicYear": "2025-2026", "taskDate": "2025-11-01", "category": "التخطيط والمتابعة", "title": "تدريب الطالب محمد الرويلي لمسابقة تايوان World Skills والسفر معه للمتابعة والإشراف لمدة أسبوع", "status": "قيد التنفيذ", "evidenceLabel": "", "evidenceUrl": "", "source": "تقارير المهام الشهرية - نوفمبر 2025", "hasEvidence": false, "completionPercentage": 50, "priority": "متوسطة", "taskType": "شهرية", "createdBy": "E-Projects Coordinator" },
  { "month": "نوفمبر", "academicYear": "2025-2026", "taskDate": "2025-11-01", "category": "المشاركات والإنجازات", "title": "المشاركة في جائزة التميز العلمي - البحث المتميز مع الطالب غالب شاجع", "status": "يوجد دليل إنجاز", "evidenceLabel": "Click Here", "evidenceUrl": "https://educationqa-my.sharepoint.com/:b:/g/personal/a_tubaishat1704_education_qa/EWIGaAL27vZHtLEclQVNNuABtJsr6rMYH8d32TraJZODsA?e=JRwtOU", "source": "تقارير المهام الشهرية - نوفمبر 2025", "hasEvidence": true, "completionPercentage": 100, "priority": "متوسطة", "taskType": "شهرية", "createdBy": "E-Projects Coordinator" },

  // February 2026
  { "month": "فبراير", "academicYear": "2025-2026", "taskDate": "2026-02-01", "category": "الاجتماعات", "title": "اجتماع البحث العلمي", "status": "مكتملة", "evidenceLabel": "DONE", "evidenceUrl": "", "source": "تقارير المهام الشهرية - فبراير 2026", "hasEvidence": false, "completionPercentage": 100, "priority": "متوسطة", "taskType": "شهرية", "createdBy": "E-Projects Coordinator" },
  { "month": "فبراير", "academicYear": "2025-2026", "taskDate": "2026-02-01", "category": "الاجتماعات", "title": "اجتماع الرواد", "status": "مكتملة", "evidenceLabel": "DONE", "evidenceUrl": "", "source": "تقارير المهام الشهرية - فبراير 2026", "hasEvidence": false, "completionPercentage": 100, "priority": "متوسطة", "taskType": "شهرية", "createdBy": "E-Projects Coordinator" },
  { "month": "فبراير", "academicYear": "2025-2026", "taskDate": "2026-02-01", "category": "الاجتماعات", "title": "اجتماع شركة Seasouchor", "status": "مكتملة", "evidenceLabel": "DONE", "evidenceUrl": "", "source": "تقارير المهام الشهرية - فبراير 2026", "hasEvidence": false, "completionPercentage": 100, "priority": "متوسطة", "taskType": "شهرية", "createdBy": "E-Projects Coordinator" },
  { "month": "فبراير", "academicYear": "2025-2026", "taskDate": "2026-02-01", "category": "الاجتماعات", "title": "اجتماعات مسابقة ITEX عدد 3", "status": "مكتملة", "evidenceLabel": "DONE", "evidenceUrl": "", "source": "تقارير المهام الشهرية - فبراير 2026", "hasEvidence": false, "completionPercentage": 100, "priority": "متوسطة", "taskType": "شهرية", "createdBy": "E-Projects Coordinator" },
  { "month": "فبراير", "academicYear": "2025-2026", "taskDate": "2026-02-01", "category": "الاجتماعات", "title": "اجتماع التحصيل الأكاديمي", "status": "مكتملة", "evidenceLabel": "DONE", "evidenceUrl": "", "source": "تقارير المهام الشهرية - فبراير 2026", "hasEvidence": false, "completionPercentage": 100, "priority": "متوسطة", "taskType": "شهرية", "createdBy": "E-Projects Coordinator" },
  { "month": "فبراير", "academicYear": "2025-2026", "taskDate": "2026-02-01", "category": "الاجتماعات", "title": "الاجتماع الثالث لمنسقي المشاريع الإلكترونية", "status": "مكتملة", "evidenceLabel": "DONE", "evidenceUrl": "", "source": "تقارير المهام الشهرية - فبراير 2026", "hasEvidence": false, "completionPercentage": 100, "priority": "متوسطة", "taskType": "شهرية", "createdBy": "E-Projects Coordinator" },
  { "month": "فبراير", "academicYear": "2025-2026", "taskDate": "2026-02-01", "category": "التطوير المهني", "title": "تدريب المعلمين الجدد حسب الخطة المتبعة", "status": "مكتملة", "evidenceLabel": "DONE", "evidenceUrl": "", "source": "تقارير المهام الشهرية - فبراير 2026", "hasEvidence": false, "completionPercentage": 100, "priority": "متوسطة", "taskType": "شهرية", "createdBy": "E-Projects Coordinator" },
  { "month": "فبراير", "academicYear": "2025-2026", "taskDate": "2026-02-01", "category": "التخطيط والمتابعة", "title": "الرسالة الأسبوعية والتقرير الشهري للطلاب", "status": "مكتملة", "evidenceLabel": "DONE", "evidenceUrl": "", "source": "تقارير المهام الشهرية - فبراير 2026", "hasEvidence": false, "completionPercentage": 100, "priority": "متوسطة", "taskType": "شهرية", "createdBy": "E-Projects Coordinator" },
  { "month": "فبراير", "academicYear": "2025-2026", "taskDate": "2026-02-01", "category": "التخطيط والمتابعة", "title": "المساعدة في الأبحاث العلمية للمدرسة", "status": "مكتملة", "evidenceLabel": "DONE", "evidenceUrl": "", "source": "تقارير المهام الشهرية - فبراير 2026", "hasEvidence": false, "completionPercentage": 100, "priority": "متوسطة", "taskType": "شهرية", "createdBy": "E-Projects Coordinator" },
  { "month": "فبراير", "academicYear": "2025-2026", "taskDate": "2026-02-01", "category": "التخطيط والمتابعة", "title": "المشاركة في مسابقة ITEX", "status": "مكتملة", "evidenceLabel": "DONE", "evidenceUrl": "", "source": "تقارير المهام الشهرية - فبراير 2026", "hasEvidence": false, "completionPercentage": 100, "priority": "متوسطة", "taskType": "شهرية", "createdBy": "E-Projects Coordinator" },
  { "month": "فبراير", "academicYear": "2025-2026", "taskDate": "2026-02-01", "category": "التخطيط والمتابعة", "title": "المشاركة في مسابقة البحث العلمي", "status": "مكتملة", "evidenceLabel": "DONE", "evidenceUrl": "", "source": "تقارير المهام الشهرية - فبراير 2026", "hasEvidence": false, "completionPercentage": 100, "priority": "متوسطة", "taskType": "شهرية", "createdBy": "E-Projects Coordinator" },
  { "month": "فبراير", "academicYear": "2025-2026", "taskDate": "2026-02-01", "category": "التخطيط والمتابعة", "title": "نشر ومتابعة الاستبيان الوطني التربوي للمعلمين والطلاب وأولياء الأمور", "status": "مكتملة", "evidenceLabel": "DONE", "evidenceUrl": "", "source": "تقارير المهام الشهرية - فبراير 2026", "hasEvidence": false, "completionPercentage": 100, "priority": "متوسطة", "taskType": "شهرية", "createdBy": "E-Projects Coordinator" },
  { "month": "فبراير", "academicYear": "2025-2026", "taskDate": "2026-02-01", "category": "التخطيط والمتابعة", "title": "المساعدة في مسابقة تحدي علوم المستقبل", "status": "مكتملة", "evidenceLabel": "DONE", "evidenceUrl": "", "source": "تقارير المهام الشهرية - فبراير 2026", "hasEvidence": false, "completionPercentage": 100, "priority": "متوسطة", "taskType": "شهرية", "createdBy": "E-Projects Coordinator" },
  { "month": "فبراير", "academicYear": "2025-2026", "taskDate": "2026-02-01", "category": "التخطيط والمتابعة", "title": "إعداد قوائم المواقع والاشتراكات السنوية", "status": "مكتملة", "evidenceLabel": "DONE", "evidenceUrl": "", "source": "تقارير المهام الشهرية - فبراير 2026", "hasEvidence": false, "completionPercentage": 100, "priority": "متوسطة", "taskType": "شهرية", "createdBy": "E-Projects Coordinator" },
  { "month": "فبراير", "academicYear": "2025-2026", "taskDate": "2026-02-01", "category": "التخطيط والمتابعة", "title": "حصص التعلم عن بعد", "status": "مكتملة", "evidenceLabel": "DONE", "evidenceUrl": "", "source": "تقارير المهام الشهرية - فبراير 2026", "hasEvidence": false, "completionPercentage": 100, "priority": "متوسطة", "taskType": "شهرية", "createdBy": "E-Projects Coordinator" },
  { "month": "فبراير", "academicYear": "2025-2026", "taskDate": "2026-02-01", "category": "التخطيط والمتابعة", "title": "البدء بعملية مشتريات المواقع والاشتراكات السنوية", "status": "مكتملة", "evidenceLabel": "DONE", "evidenceUrl": "", "source": "تقارير المهام الشهرية - فبراير 2026", "hasEvidence": false, "completionPercentage": 100, "priority": "متوسطة", "taskType": "شهرية", "createdBy": "E-Projects Coordinator" },
  { "month": "فبراير", "academicYear": "2025-2026", "taskDate": "2026-02-01", "category": "التخطيط والمتابعة", "title": "تقديم الملفات لمسابقة ITEX وتدريب الطلاب", "status": "مكتملة", "evidenceLabel": "DONE", "evidenceUrl": "", "source": "تقارير المهام الشهرية - فبراير 2026", "hasEvidence": false, "completionPercentage": 100, "priority": "متوسطة", "taskType": "شهرية", "createdBy": "E-Projects Coordinator" },

  // March 2026
  { "month": "مارس", "academicYear": "2025-2026", "taskDate": "2026-03-01", "category": "الاجتماعات", "title": "اجتماع التحصيل الأكاديمي", "status": "مكتملة", "evidenceLabel": "DONE", "evidenceUrl": "", "source": "تقارير المهام الشهرية - مارس 2026", "hasEvidence": false, "completionPercentage": 100, "priority": "متوسطة", "taskType": "شهرية", "createdBy": "E-Projects Coordinator" },
  { "month": "مارس", "academicYear": "2025-2026", "taskDate": "2026-03-01", "category": "الاجتماعات", "title": "اجتماع الرواد", "status": "مكتملة", "evidenceLabel": "DONE", "evidenceUrl": "", "source": "تقارير المهام الشهرية - مارس 2026", "hasEvidence": false, "completionPercentage": 100, "priority": "متوسطة", "taskType": "شهرية", "createdBy": "E-Projects Coordinator" },
  { "month": "مارس", "academicYear": "2025-2026", "taskDate": "2026-03-01", "category": "الاجتماعات", "title": "اجتماع لجنة الاعتماد الدولي Cognia", "status": "مكتملة", "evidenceLabel": "DONE", "evidenceUrl": "", "source": "تقارير المهام الشهرية - مارس 2026", "hasEvidence": false, "completionPercentage": 100, "priority": "متوسطة", "taskType": "شهرية", "createdBy": "E-Projects Coordinator" },
  { "month": "مارس", "academicYear": "2025-2026", "taskDate": "2026-03-01", "category": "الاجتماعات", "title": "اجتماع لجنة الأمن والسلامة", "status": "مكتملة", "evidenceLabel": "DONE", "evidenceUrl": "", "source": "تقارير المهام الشهرية - مارس 2026", "hasEvidence": false, "completionPercentage": 100, "priority": "متوسطة", "taskType": "شهرية", "createdBy": "E-Projects Coordinator" },
  { "month": "مارس", "academicYear": "2025-2026", "taskDate": "2026-03-01", "category": "الاجتماعات", "title": "اجتماعات التعليم الإلكتروني عن بعد: اجتماعات الإدارة واجتماعات الوزارة", "status": "مكتملة", "evidenceLabel": "DONE", "evidenceUrl": "", "source": "تقارير المهام الشهرية - مارس 2026", "hasEvidence": false, "completionPercentage": 100, "priority": "متوسطة", "taskType": "شهرية", "createdBy": "E-Projects Coordinator" },
  { "month": "مارس", "academicYear": "2025-2026", "taskDate": "2026-03-01", "category": "التطوير المهني", "title": "تدريب المعلمين على التعلم عن بعد وإرسال إرشادات لهم بشكل فردي وجماعي", "status": "مكتملة", "evidenceLabel": "DONE", "evidenceUrl": "", "source": "تقارير المهام الشهرية - مارس 2026", "hasEvidence": false, "completionPercentage": 100, "priority": "متوسطة", "taskType": "شهرية", "createdBy": "E-Projects Coordinator" },
  { "month": "مارس", "academicYear": "2025-2026", "taskDate": "2026-03-01", "category": "التطوير المهني", "title": "ورشة أولياء الأمور للتعلم عن بعد", "status": "مكتملة", "evidenceLabel": "DONE", "evidenceUrl": "", "source": "تقارير المهام الشهرية - مارس 2026", "hasEvidence": false, "completionPercentage": 100, "priority": "متوسطة", "taskType": "شهرية", "createdBy": "E-Projects Coordinator" },
  { "month": "مارس", "academicYear": "2025-2026", "taskDate": "2026-03-01", "category": "التخطيط والمتابعة", "title": "الرسالة الأسبوعية والتقرير الشهري للطلاب", "status": "مكتملة", "evidenceLabel": "DONE", "evidenceUrl": "", "source": "تقارير المهام الشهرية - مارس 2026", "hasEvidence": false, "completionPercentage": 100, "priority": "متوسطة", "taskType": "شهرية", "createdBy": "E-Projects Coordinator" },
  { "month": "مارس", "academicYear": "2025-2026", "taskDate": "2026-03-01", "category": "التخطيط والمتابعة", "title": "متابعة التعلم عن بعد", "status": "مكتملة", "evidenceLabel": "DONE", "evidenceUrl": "", "source": "تقارير المهام الشهرية - مارس 2026", "hasEvidence": false, "completionPercentage": 100, "priority": "متوسطة", "taskType": "شهرية", "createdBy": "E-Projects Coordinator" },
  { "month": "مارس", "academicYear": "2025-2026", "taskDate": "2026-03-01", "category": "التخطيط والمتابعة", "title": "تقديم الملفات في موقع مسابقة ITEX", "status": "مكتملة", "evidenceLabel": "DONE", "evidenceUrl": "", "source": "تقارير المهام الشهرية - مارس 2026", "hasEvidence": false, "completionPercentage": 100, "priority": "متوسطة", "taskType": "شهرية", "createdBy": "E-Projects Coordinator" },
  { "month": "مارس", "academicYear": "2025-2026", "taskDate": "2026-03-01", "category": "التخطيط والمتابعة", "title": "متابعة حصص التعلم عن بعد", "status": "مكتملة", "evidenceLabel": "DONE", "evidenceUrl": "", "source": "تقارير المهام الشهرية - مارس 2026", "hasEvidence": false, "completionPercentage": 100, "priority": "متوسطة", "taskType": "شهرية", "createdBy": "E-Projects Coordinator" },
  { "month": "مارس", "academicYear": "2025-2026", "taskDate": "2026-03-01", "category": "التخطيط والمتابعة", "title": "توثيق إجراءات التعلم عن بعد", "status": "مكتملة", "evidenceLabel": "DONE", "evidenceUrl": "", "source": "تقارير المهام الشهرية - مارس 2026", "hasEvidence": false, "completionPercentage": 100, "priority": "متوسطة", "taskType": "شهرية", "createdBy": "E-Projects Coordinator" },
  { "month": "مارس", "academicYear": "2025-2026", "taskDate": "2026-03-01", "category": "التخطيط والمتابعة", "title": "اختبارات القبول والعمل عليها لمدة أسبوعين: كنترول، مراقبة، تنظيم، وتخطيط", "status": "مكتملة", "evidenceLabel": "DONE", "evidenceUrl": "", "source": "تقارير المهام الشهرية - مارس 2026", "hasEvidence": false, "completionPercentage": 100, "priority": "متوسطة", "taskType": "شهرية", "createdBy": "E-Projects Coordinator" },
  { "month": "مارس", "academicYear": "2025-2026", "taskDate": "2026-03-01", "category": "التخطيط والمتابعة", "title": "نشر جداول اختبارات منتصف الفصل الدراسي الثاني", "status": "مكتملة", "evidenceLabel": "DONE", "evidenceUrl": "", "source": "تقارير المهام الشهرية - مارس 2026", "hasEvidence": false, "completionPercentage": 100, "priority": "متوسطة", "taskType": "شهرية", "createdBy": "E-Projects Coordinator" },

  // April 2026
  { "month": "أبريل", "academicYear": "2025-2026", "taskDate": "2026-04-01", "category": "الاجتماعات", "title": "اجتماع التحصيل الأكاديمي", "status": "مكتملة", "evidenceLabel": "DONE", "evidenceUrl": "", "source": "تقارير المهام الشهرية - أبريل 2026", "hasEvidence": false, "completionPercentage": 100, "priority": "متوسطة", "taskType": "شهرية", "createdBy": "E-Projects Coordinator" },
  { "month": "أبريل", "academicYear": "2025-2026", "taskDate": "2026-04-01", "category": "الاجتماعات", "title": "اجتماع الرواد", "status": "مكتملة", "evidenceLabel": "DONE", "evidenceUrl": "", "source": "تقارير المهام الشهرية - أبريل 2026", "hasEvidence": false, "completionPercentage": 100, "priority": "متوسطة", "taskType": "شهرية", "createdBy": "E-Projects Coordinator" },
  { "month": "أبريل", "academicYear": "2025-2026", "taskDate": "2026-04-01", "category": "الاجتماعات", "title": "اجتماع الاعتماد الدولي Cognia", "status": "مكتملة", "evidenceLabel": "DONE", "evidenceUrl": "", "source": "تقارير المهام الشهرية - أبريل 2026", "hasEvidence": false, "completionPercentage": 100, "priority": "متوسطة", "taskType": "شهرية", "createdBy": "E-Projects Coordinator" },
  { "month": "أبريل", "academicYear": "2025-2026", "taskDate": "2026-04-01", "category": "التطوير المهني", "title": "فيديو التعلم عن بعد ونشره", "status": "مكتملة", "evidenceLabel": "DONE", "evidenceUrl": "", "source": "تقارير المهام الشهرية - أبريل 2026", "hasEvidence": false, "completionPercentage": 100, "priority": "متوسطة", "taskType": "شهرية", "createdBy": "E-Projects Coordinator" },
  { "month": "أبريل", "academicYear": "2025-2026", "taskDate": "2026-04-01", "category": "التخطيط والمتابعة", "title": "البدء بتجهيز الملفات والمعايير ورفعها للاعتماد الدولي Cognia لمدة أسبوعين", "status": "مكتملة", "evidenceLabel": "DONE", "evidenceUrl": "", "source": "تقارير المهام الشهرية - أبريل 2026", "hasEvidence": false, "completionPercentage": 100, "priority": "متوسطة", "taskType": "شهرية", "createdBy": "E-Projects Coordinator" },
  { "month": "أبريل", "academicYear": "2025-2026", "taskDate": "2026-04-01", "category": "التخطيط والمتابعة", "title": "نشر جداول الاختبارات العملية والنظرية واختبارات منتصف الفصل الدراسي الثاني 2026", "status": "مكتملة", "evidenceLabel": "DONE", "evidenceUrl": "", "source": "تقارير المهام الشهرية - أبريل 2026", "hasEvidence": false, "completionPercentage": 100, "priority": "متوسطة", "taskType": "شهرية", "createdBy": "E-Projects Coordinator" },
  { "month": "أبريل", "academicYear": "2025-2026", "taskDate": "2026-04-01", "category": "التخطيط والمتابعة", "title": "متابعة اختبارات القبول للطلاب الجدد لمدارس قطر للعلوم والتكنولوجيا الجديدة", "status": "مكتملة", "evidenceLabel": "DONE", "evidenceUrl": "", "source": "تقارير المهام الشهرية - أبريل 2026", "hasEvidence": false, "completionPercentage": 100, "priority": "متوسطة", "taskType": "شهرية", "createdBy": "E-Projects Coordinator" },
  { "month": "أبريل", "academicYear": "2025-2026", "taskDate": "2026-04-01", "category": "التخطيط والمتابعة", "title": "المشاركة في تقديم 3 مبادرات متميزة في التعليم عن بعد للتعليم الإلكتروني", "status": "مكتملة", "evidenceLabel": "DONE", "evidenceUrl": "", "source": "تقارير المهام الشهرية - أبريل 2026", "hasEvidence": false, "completionPercentage": 100, "priority": "متوسطة", "taskType": "شهرية", "createdBy": "E-Projects Coordinator" }
];

export const SEED_NOTES = [
  {
    "month": "فبراير",
    "academicYear": "2025-2026",
    "note": "فترة رمضان وحصص التعلم عن بعد.",
    "source": "تقارير المهام الشهرية - فبراير 2026"
  },
  {
    "month": "مارس",
    "academicYear": "2025-2026",
    "note": "تم عقد اختبارات قبول الطلاب الجدد لمدارس قطر للعلوم والتكنولوجيا إلكترونيًا، كما كانت الدراسة عن بعد لمدة أسبوعين، إضافة إلى متابعة أعمال الكنترول والتنظيم والتخطيط.",
    "source": "تقارير المهام الشهرية - مارس 2026"
  },
  {
    "month": "أبريل",
    "academicYear": "2025-2026",
    "note": "يوجد اختبارات قبول في أول أسبوع من شهر أبريل، إضافة إلى اختبارات منتصف الفصل الدراسي الثاني.",
    "source": "تقارير المهام الشهرية - أبريل 2026"
  }
];

export const SEED_ACHIEVEMENTS = [
  // 2021/2022
  { serialNumber: 33, academicYear: '2021-2022', organizer: 'وزارة التعليم والتعليم العالي', level: 'محلي', participationType: 'إشراف وتدريب', result: 'جائزة خاصة', achievementName: 'مسابقة البحث العلمي والابتكار 2022' },

  // 2022/2023
  { serialNumber: 8, academicYear: '2022-2023', organizer: 'GYSTB – هونغ كونغ', level: 'عالمي', participationType: 'إشراف وتدريب', result: 'المركز الثالث', achievementName: 'مسابقة البحث العلمي GYSTB – هونغ كونغ' },
  { serialNumber: 13, academicYear: '2022-2023', organizer: 'مؤسسة حمدان بن راشد - الإمارات', level: 'إقليمي', participationType: 'إشراف وتدريب', result: 'المركز الأول', achievementName: 'بطل مسابقة تحدي علوم المستقبل - الموسم الثاني' },
  { serialNumber: 18, academicYear: '2022-2023', organizer: 'وزارة التعليم والتعليم العالي', level: 'محلي', participationType: 'إشراف وتدريب', result: 'المركز الثاني', achievementName: 'مسابقة البحث العلمي والابتكار' },
  { serialNumber: 32, academicYear: '2022-2023', organizer: 'وزارة التعليم والتعليم العالي', level: 'محلي', participationType: 'إشراف وتدريب', result: 'المركز الثالث', achievementName: 'بطولة قطر للروبوت' },
  { serialNumber: 34, academicYear: '2022-2023', organizer: 'وزارة التعليم والتعليم العالي', level: 'محلي', participationType: 'إشراف وتدريب', result: 'جائزة خاصة', achievementName: 'مسابقة البحث العلمي والابتكار 2023' },

  // 2023/2024
  { serialNumber: 6, academicYear: '2023-2024', organizer: 'اليونيسكو', level: 'عالمي', participationType: 'إشراف وتدريب', result: 'المركز الثاني', achievementName: 'المؤتمر الدولي للذكاء الاصطناعي في كازاخستان' },
  { serialNumber: 7, academicYear: '2023-2024', organizer: 'المعرض الدولي للاختراعات في الشرق الأوسط - الكويت', level: 'عالمي', participationType: 'إشراف وتدريب', result: 'المركز الأول', achievementName: 'المعرض الدولي للاختراعات في الشرق الأوسط - الكويت' },
  { serialNumber: 12, academicYear: '2023-2024', organizer: 'مؤسسة حمدان بن راشد - الإمارات', level: 'إقليمي', participationType: 'إشراف وتدريب', result: 'المركز الأول', achievementName: 'بطل مسابقة تحدي علوم المستقبل - الموسم الثالث' },
  { serialNumber: 14, academicYear: '2023-2024', organizer: 'الجمعية العربية للروبوت', level: 'إقليمي', participationType: 'إشراف وتدريب', result: 'المركز الثالث', achievementName: 'البطولة العربية للروبوت - ذراع الروبوت' },
  { serialNumber: 16, academicYear: '2023-2024', organizer: 'جامعة قطر', level: 'محلي', participationType: 'إشراف وتدريب', result: 'المركز الأول والمركز الثاني', achievementName: 'المسابقة الوطنية للذكاء الاصطناعي' },
  { serialNumber: 17, academicYear: '2023-2024', organizer: 'وزارة التعليم والتعليم العالي', level: 'محلي', participationType: 'إشراف وتدريب', result: 'المركز الأول', achievementName: 'مسابقة البحث العلمي والابتكار' },
  { serialNumber: 19, academicYear: '2023-2024', organizer: 'وزارة التعليم والتعليم العالي', level: 'محلي', participationType: 'إشراف وتدريب', result: 'المركز الأول', achievementName: 'الأولمبياد الوطني للذكاء الاصطناعي والبرمجة' },
  { serialNumber: 22, academicYear: '2023-2024', organizer: 'اللجنة الوطنية لحظر الأسلحة', level: 'محلي', participationType: 'إشراف وتدريب', result: 'المركز الأول', achievementName: 'مسابقة البحث العلمي للوكالة الوطنية لحظر أسلحة الدمار الشامل' },
  { serialNumber: 24, academicYear: '2023-2024', organizer: 'وزارة التعليم والتعليم العالي', level: 'محلي', participationType: 'إشراف وتدريب', result: 'المركز الأول', achievementName: 'مسابقة قطر المستقبل للاستدامة' },
  { serialNumber: 27, academicYear: '2023-2024', organizer: 'وزارة التعليم والتعليم العالي', level: 'محلي', participationType: 'إشراف وتدريب', result: 'الميدالية الذهبية', achievementName: 'باحث 5' },
  { serialNumber: 28, academicYear: '2023-2024', organizer: 'النادي العلمي القطري', level: 'محلي', participationType: 'إشراف وتدريب', result: 'الميدالية الذهبية', achievementName: 'باحث 7' },
  { serialNumber: 30, academicYear: '2023-2024', organizer: 'وزارة التعليم والتعليم العالي', level: 'محلي', participationType: 'إشراف وتدريب', result: 'المركز الثاني', achievementName: 'الأولمبياد الوطني للروبوت' },
  { serialNumber: 31, academicYear: '2023-2024', organizer: 'وزارة التعليم والتعليم العالي', level: 'محلي', participationType: 'إشراف وتدريب', result: 'المركز الثاني', achievementName: 'مسابقة جيل الإبداع الرقمي' },

  // 2024/2025
  { serialNumber: 1, academicYear: '2024-2025', organizer: 'ISEF - USA', level: 'عالمي', participationType: 'إشراف وتدريب', result: 'تمثيل دولة قطر', achievementName: 'التأهل لنهائيات مسابقة البحث العلمي العالمية ISEF - USA' },
  { serialNumber: 2, academicYear: '2024-2025', organizer: 'Earth Foundation - سويسرا', level: 'عالمي', participationType: 'إشراف وتدريب', result: 'أفضل خمس مشاريع في الشرق الأوسط', achievementName: 'The Earth Prize 2025' },
  { serialNumber: 5, academicYear: '2024-2025', organizer: 'USA', level: 'عالمي', participationType: 'إشراف وتدريب', result: 'المركز الثاني', achievementName: 'SDG Gamechanger Award' },
  { serialNumber: 10, academicYear: '2024-2025', organizer: 'وزارة التعليم والتعليم العالي', level: 'إقليمي', participationType: 'إشراف وتدريب', result: 'المركز الأول', achievementName: 'الأولمبياد العربي للذكاء الاصطناعي والبرمجة والأمن السيبراني' },
  { serialNumber: 11, academicYear: '2024-2025', organizer: 'مؤسسة حمدان بن راشد - الإمارات', level: 'إقليمي', participationType: 'إشراف وتدريب', result: 'المركز الأول', achievementName: 'جائزة أفضل مهندس - الموسم الرابع - مسابقة تحدي علوم المستقبل' },
  { serialNumber: 15, academicYear: '2024-2025', organizer: 'الجمعية العربية للروبوت والذكاء الاصطناعي', level: 'إقليمي', participationType: 'إشراف وتدريب', result: 'المركز الأول', achievementName: 'البطولة العربية للذكاء الاصطناعي' },
  { serialNumber: 20, academicYear: '2024-2025', organizer: 'واحة قطر للعلوم والتكنولوجيا QSTP', level: 'محلي', participationType: 'إشراف وتدريب', result: 'المركز الأول والمركز الثاني', achievementName: 'هاكثون الذكاء الاصطناعي للمدارس التخصصية والتقنية' },
  { serialNumber: 21, academicYear: '2024-2025', organizer: 'وزارة التعليم والتعليم العالي', level: 'محلي', participationType: 'إشراف وتدريب', result: 'المركز الثاني', achievementName: 'مسابقة البحث العلمي والابتكار' },
  { serialNumber: 23, academicYear: '2024-2025', organizer: 'كهرماء', level: 'محلي', participationType: 'إشراف وتدريب', result: 'المركز الأول', achievementName: 'مسابقة ترشيد كهرماء' },
  { serialNumber: 25, academicYear: '2024-2025', organizer: 'وزارة التعليم والتعليم العالي', level: 'محلي', participationType: 'إشراف وتدريب', result: 'المركز الأول', achievementName: 'مسابقة USDT - Skills Day جامعة الدوحة للعلوم والتكنولوجيا' },
  { serialNumber: 26, academicYear: '2024-2025', organizer: 'النادي العلمي القطري', level: 'محلي', participationType: 'إشراف وتدريب', result: 'الميدالية الذهبية', achievementName: 'باحث 6' },
  { serialNumber: 29, academicYear: '2024-2025', organizer: 'النادي العلمي القطري', level: 'محلي', participationType: 'إشراف وتدريب', result: 'الميدالية الذهبية', achievementName: 'مسابقة ابتكار' },
  { serialNumber: 35, academicYear: '2024-2025', organizer: 'وزارة التعليم والتعليم العالي', level: 'محلي', participationType: 'إشراف وتدريب', result: 'جائزة خاصة', achievementName: 'مسابقة البحث العلمي 2024' },
  { serialNumber: 36, academicYear: '2024-2025', organizer: 'وزارة التعليم والتعليم العالي', level: 'محلي', participationType: 'إشراف وتدريب', result: 'المركز الأول', achievementName: 'بطولة قطر للذكاء الاصطناعي' },
  { serialNumber: 38, academicYear: '2024-2025', organizer: 'World Skills Asia - Taiwan', level: 'إقليمي', participationType: 'إشراف وتدريب', result: 'تمثيل دولة قطر', achievementName: 'التأهل لمسابقة World Skills الآسيوية' },

  // 2025/2026
  { serialNumber: 3, academicYear: '2025-2026', organizer: 'IEEE', level: 'عالمي', participationType: 'نشر بحث علمي', result: 'بحث علمي منشور', achievementName: 'نشر بحث علمي في مجلة IEEE' },
  { serialNumber: 4, academicYear: '2025-2026', organizer: 'ITEX / مسابقة البحث العلمي', level: 'عالمي', participationType: 'إشراف وتدريب', result: 'المركز الثاني + التأهل العالمي', achievementName: 'مسابقة البحث العلمي والتأهل إلى ITEX العالمية' },
  { serialNumber: 9, academicYear: '2025-2026', organizer: 'SmartNet', level: 'عالمي', participationType: 'نشر بحث علمي', result: 'بحث علمي منشور', achievementName: 'نشر بحث علمي في مجلة SmartNet' },
  { serialNumber: 37, academicYear: '2025-2026', organizer: 'Google Scholar', level: 'عالمي', participationType: 'إشراف وتدريب', result: 'بحث علمي منشور', achievementName: 'نشر بحث علمي في موقع Google Scholar' },
  { serialNumber: 39, academicYear: '2025-2026', organizer: 'وزارة التعليم والتعليم العالي', level: 'محلي', participationType: 'إشراف وتدريب', result: 'التأهل للمعرض', achievementName: 'التأهل لمسابقة البحث العلمي والابتكار لسنة 2025-2026' }
];
